### PR TITLE
Update vscode-php-debug to 1.23.0

### PR DESCRIPTION
**Pull request by przepompownia**
See https://github.com/xdebug/vscode-php-debug/releases/tag/v1.23.0

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/523)

**Comment by puremourning** [comment]
Thanks. Does the set variable work with vimspector?

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/523#-:-Mu2IxKm49u1SbdGQxiu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @przepompownia)

**Comment by przepompownia** [comment]
> Thanks. Does the set variable work with vimspector?

image
It works - on the screenshot `createClientCapabilities()` was called with `$completion = true` from line 395.

**Comment by puremourning** [comment]
świetnie, dzięki.

**Pull request merged**
