### PR TITLE
Document how to use debugpy directly instead of vscode-python

### LINKED ISSUE #105: Unable to debug python with node 13 environment. "Number of constructor arguments..."
**Describe the bug**

Starting to debug a basic python file opens vimspector windows but no debugging starts. Vimspector encounters an error and crashes.

**To Reproduce**

* `vim test.py`
* `iprint('hello')`
* `<f5>`

Vimspector config file:

```json
{
  "configurations": {
    "univisal: Launch": {
      "adapter": "vscode-python",
      "configuration": {
        "name": "<name>: Launch",
        "type": "python",
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "stopOnEntry": true,
        "console": "externalTerminal",
        "debugOptions": [],
        "program": "${file}"
      }
    }
  }
}
```

**Expected behavior**

A debugging session starts

**Actual behaviour**

Vimspector windows open but no debugging starts.

No output except stderr, and that was the same as the contents of the log.

**Environemnt**

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

c6c0144f85a79baa0664c1fa145c029820e2b293

* Output of `vim --version` or `nvim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 26 2020 11:45:38)
Included patches: 1-148
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       +tcl/dyn
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl/dyn          +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

* Output of `which vim` or `which nvim`:

```
/usr/bin/vim
```

* Output of `:py3 pass`: no output

* Output of `:py3 import vim`: No output

* Operating system: Arch linux updated today

Vimspector.log:

```
2020-01-30 21:51:13,867 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****
2020-01-30 21:51:13,867 - INFO - API is: 
2020-01-30 21:51:13,867 - INFO - VIMSPECTOR_HOME = /home/user/.vim/plugins/vimspector
2020-01-30 21:51:13,868 - INFO - gadgetDir = /home/user/.vim/plugins/vimspector/gadgets/linux
2020-01-30 21:52:20,008 - INFO - User requested start debug session with {}
2020-01-30 21:52:20,009 - DEBUG - Reading gadget config: /home/user/.vim/plugins/vimspector/gadgets/linux/.gadgets.json
2020-01-30 21:52:20,010 - DEBUG - Reading gadget config: None
2020-01-30 21:52:20,011 - INFO - Configuration: {"adapter": "vscode-python", "configuration": {"name": "<name>: Launch", "type": "python", "request": "launch", "cwd": "/home/user/src/Univisal", "stopOnEntry": true, "console": "externalTerminal", "debugOptions": [], "program": "/home/user/src/Univisal/test.py"}}
2020-01-30 21:52:20,011 - INFO - Adapter: {"command": ["node", "/home/user/.vim/plugins/vimspector/gadgets/linux/vscode-python/out/client/debugger/debugAdapter/main.js"], "name": "vscode-python"}
2020-01-30 21:52:20,444 - INFO - Starting debug adapter with: {"command": ["node", "/home/user/.vim/plugins/vimspector/gadgets/linux/vscode-python/out/client/debugger/debugAdapter/main.js"], "name": "vscode-python"}
2020-01-30 21:52:20,534 - INFO - Debug Adapter Started
2020-01-30 21:52:20,534 - DEBUG - Sending Message: {"command": "initialize", "arguments": {"adapterID": "vscode-python", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}
2020-01-30 21:52:20,534 - DEBUG - Calling: vimspector#internal#job#Send(g:vimspector_internal_arg_0)
2020-01-30 21:52:20,566 - DEBUG - Message received: {'seq': 0, 'type': 'event', 'event': 'error', 'body': 'Debugger Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.'}
2020-01-30 21:52:20,567 - WARNING - User Msg: Unhandled event: error
2020-01-30 21:52:20,567 - DEBUG - Message received: {'seq': 0, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': 'Debugger Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.\nDebugger Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.\nError\nError: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.\n    at /home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:16:27311\n    at Array.forEach (<anonymous>)\n    at e (/home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:16:26875)\n    at Object.t.plan (/home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:16:27386)\n    at /home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:16:24044\n    at e._get (/home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:16:23953)\n    at e.get (/home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:16:22664)\n    at s.get (/home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:68:141080)\n    at new _ (/home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:1:268522)\n    at /home/user/.vim/plugins/vimspector/gadgets/linux/download/vscode-python/2019.11.50794/root/extension/out/client/debugger/debugAdapter/main.js:1:271764'}}
2020-01-30 21:52:20,603 - INFO - The server has terminated with status 0
2020-01-30 21:52:20,603 - DEBUG - Closing down: Aborting request {'command': 'initialize', 'arguments': {'adapterID': 'vscode-python', 'clientID': 'vimspector', 'clientName': 'vimspector', 'linesStartAt1': True, 'columnsStartAt1': True, 'locale': 'en_GB', 'pathFormat': 'path', 'supportsVariableType': True, 'supportsVariablePaging': False, 'supportsRunInTerminalRequest': True}, 'seq': 0, 'type': 'request'}
2020-01-30 21:52:20,603 - INFO - User Msg: Request for initialize aborted: Closing down
2020-01-30 21:52:20,637 - DEBUG - No server exit handler
2020-01-30 21:52:23,597 - INFO - Debugging complete.
2020-01-30 21:52:23,598 - DEBUG - Clearing down UI with stack_trace: ['  File "<string>", line 1, in <module>\n', '  File "/home/user/.vim//plugins/vimspector/python3/vimspector/debug_session.py", line 300, in Reset\n    self._Reset()\n', '  File "/home/user/.vim//plugins/vimspector/python3/vimspector/debug_session.py", line 306, in _Reset\n    traceback.format_stack() )\n']
```

### PR DESCRIPTION
**Pull request by puremourning**
Fixes #105

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/108)

**Comment by oblitum** [comment]
I got this error when trying it out:

```
E+00000.011: Error parsing 'DEBUGPY_LAUNCHER_PORT':

             Traceback (most recent call last):
               File "/home/francisco/.pyenv/versions/debugpy/lib/python3.8/site
-packages/debugpy/launcher/__main__.py", line 36, in option
                 return type(os.environ.pop(name, *args))
               File "/home/francisco/.pyenv/versions/debugpy/lib/python3.8/_col
lections_abc.py", line 795, in pop
                 value = self[key]
               File "/home/francisco/.pyenv/versions/debugpy/lib/python3.8/os.p
y", line 673, in __getitem__
                 raise KeyError(key) from None
             KeyError: 'DEBUGPY_LAUNCHER_PORT'

             Stack where logged:
               File "/usr/lib64/python3.8/runpy.py", line 193, in _run_module_a
s_main
                 return _run_code(code, main_globals, None,
               File "/usr/lib64/python3.8/runpy.py", line 86, in _run_code
                 exec(code, run_globals)
               File "/home/francisco/.pyenv/versions/debugpy/lib/python3.8/site
-packages/debugpy/launcher/__main__.py", line 80, in <module>
                 main()
               File "/home/francisco/.pyenv/versions/debugpy/lib/python3.8/site
-packages/debugpy/launcher/__main__.py", line 40, in main
                 launcher_port = option("DEBUGPY_LAUNCHER_PORT", int)
               File "/home/francisco/.pyenv/versions/debugpy/lib/python3.8/site
-packages/debugpy/launcher/__main__.py", line 38, in option
                 raise log.exception("Error parsing {0!r}:", name)
```

I installed `debugpy` in a pyenv virtual enviroment for it b/c I don't like to `pip install` globally, but it seemed OK when executed from command line.

`debugpy.json`:
```json
{
  "adapters": {
    "debugpy": {
      "command": [
        "/home/francisco/.pyenv/versions/debugpy/bin/python",
        "-m",
        "debugpy.adapter"
      ],
      "name": "debugpy",
      "configuration": {
        "python": "python"
      }
    }
  }
}
```

`.vimspector.json`:
```json
{
  "configurations": {
    "Launch": {
      "adapter": "debugpy",
      "configuration": {
        "type": "python",
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "stopOnEntry": true,
        "console": "externalTerminal",
        "program": "${workspaceRoot}/sample.py"
      }
    }
  }
}
```

**Comment by puremourning** [comment]
Oh, you're using neovim. Bad luck.

Apparently, you can't set environment variables when launching a term with neovim:

```
		{opts} is a dictionary with these keys:
		  |on_stdout|: stdout event handler (function name or |Funcref|)
		  stdout_buffered : read stdout in |channel-buffered| mode.
		  |on_stderr|: stderr event handler (function name or |Funcref|)
		  stderr_buffered : read stderr in |channel-buffered| mode.
		  |on_exit|  : exit event handler (function name or |Funcref|)
		  cwd      : Working directory of the job; defaults to
		             |current-directory|.
		  rpc      : If set, |msgpack-rpc| will be used to communicate
			     with the job over stdin and stdout. "on_stdout" is
			     then ignored, but "on_stderr" can still be used.
		  pty      : If set, the job will be connected to a new pseudo
			     terminal and the job streams are connected to the
			     master file descriptor. "on_stderr" is ignored,
			     "on_stdout" receives all output.

		  width    : (pty only) Width of the terminal screen
		  height   : (pty only) Height of the terminal screen
		  TERM     : (pty only) $TERM environment variable
		  detach   : (non-pty only) Detach the job process: it will
			     not be killed when Nvim exits. If the process
			     exits before Nvim, "on_exit" will be invoked.
```

I'm told this works in neovim master... do you know what the key is in `:help jobstart-options` ?

**Comment by oblitum** [comment]
> do you know what the key is in `:help jobstart-options` ?

No idea.

**Comment by puremourning** [comment]
hmmm what version of neovim are you using ?

I'm using this:

```
  let s:job = jobstart( a:config[ 'command' ],
        \                {
        \                    'on_stdout': funcref( 's:_OnEvent' ),
        \                    'on_stderr': funcref( 's:_OnEvent' ),
        \                    'on_exit': funcref( 's:_OnEvent' ),
        \                    'cwd': a:config[ 'cwd' ],
        \                    'env': a:config[ 'env' ],
        \                }
        \              )

```

which according to https://github.com/neovim/neovim/blob/master/runtime/doc/eval.txt#L5466 should work in master

**Comment by oblitum** [comment]
I use latest release. I only used nightly for the floating windows, after it was released I happily stopped living on the edge.

**Comment by puremourning** [comment]
> I use latest release. I only used nightly for the floating windows, after it was released I happily stopped living on the edge.

Bummer. You'll have to wait for the next release then, because this is a neovim limitation

**Comment by oblitum** [comment]
If it requires master, no worries. I can wait for the next release, sometime, in the remote future.

**Comment by puremourning** [comment]
I added a note that it doesn't work in neovim 0.4

**Pull request merged**
