### PR TITLE
Fix typo 'suport' -> 'support'

### PR DESCRIPTION
**Pull request by mark2185**

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/698)

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/698#-:-NFVLh-i1Sx7LlMIY4y0:b4p60j0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mark2185)

**Comment by mark2185** [comment]
The CI knows I don't like apple.

**Review by puremourning — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/698#-:-NFjcUM714_g6B8OhrGJ:b-uwkowd)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mark2185)

**Review by puremourning — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/698#-:-NFjcUM714_g6B8OhrGJ:b-uwkowd)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mark2185)

**Pull request merged**
