### PR TITLE
Update vscode-php-debug to 1.25.0

### PR DESCRIPTION
**Pull request by przepompownia**
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.25.0

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/540)

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/540#-:-MxFhqBR5AnWuF0oroHq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @przepompownia)

**Comment by przepompownia** [comment]
@puremourning can you resolve the problem on MacOS test environment?

**Comment by puremourning** [comment]
I’ll re run it. Maybe flake.

**Pull request merged**
