### PR TITLE
Fix installation issues on windows - find npm.cmd

### LINKED ISSUE #259: Installing vscode-node-debug on Windows
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug

When trying to install node debugger with: `install_gadget.py --force-enable-node`, I got a file not found error

I resolved the bug for this command by temporarily changing the python3/vimspector/installer.py at line 67 from
` subprocess.check_call( *args, **kwargs )` to `subprocess.check_call( *args, shell=True)`

### Minimal reproduciton

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ? \[No]
* If you are using Neovim, does your issue reproduce using Vim? \[Yes]

> List of steps to reproduce:

> 1. Run `install_gadget.py --force-enable-node` (on Windows, python 3.8)

> Use the following Vimspector config file:

Non vim related bug

### Expected behaviour

output of command
```
...
The following adapters were installed successfully:
 - vscode-node-debug2
```

### Actual behaviour
```
Traceback (most recent call last):
  File "python3\vimspector\installer.py", line 463, in InstallGagdet
    gadget[ 'do' ]( name, root, spec )
  File "python3\vimspector\gadgets.py", line 389, in <lambda>
    'do': lambda name, root, gadget: installer.InstallNodeDebug( name,
  File "python3\vimspector\installer.py", line 387, in InstallNodeDebug
    CheckCall( [ 'npm', 'install' ] )
  File "python3\vimspector\installer.py", line 68, in CheckCall
    subprocess.check_call( *args, **kwargs )
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Installing vscode-node-debug2@v1.42.5...
 - FAILED installing vscode-node-debug2: [WinError 2] The system cannot find the file specified
Failed to install adapters:
 * vscode-node-debug2
```

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)
Installed with VimPlug

* Output of `vim --version` or `nvim --version`

```
NVIM v0.5.0-693-g20f7b9428
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
```

* Operating system: Windows
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes]

### PR DESCRIPTION
**Pull request by puremourning**
Fixes #259

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/260)

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/260)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[python3/vimspector/installer.py, line 95 at r1](https://reviewable.io/reviews/puremourning/vimspector/260#-MHXG-ob4lC26TbGcP4o:-MHXG-ob4lC26TbGcP4p:b-rusp92) ([raw file](https://github.com/puremourning/vimspector/blob/171a093505ee0e4d6619d1117d200e1d81e40f21/python3/vimspector/installer.py#L95)):*
> ```Python
>       return filename
> 
>   raise MissingExecutable( f"Unable to find executable { executable } in any of"
> ```

too many `in any of`

**Review by aaronhallaert — APPROVED** [review]
The installation with --force-enable-node (see related issue) runs now as expected

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/260#-:-MHXoug54Eq0XeFgz9VU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
