### PR TITLE
Document closing the debugger

### PR DESCRIPTION
**Pull request by orlangure**
Thank you for this project!

After trying this out, I couldn't figure out how to return close the debugger, which turned out to be pretty simple. I suggest to document it as a part of a regular debugging flow.

This PR also includes a couple of other fixes to readme.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/75)

**Comment by orlangure** [comment]
> Better to link to the mappings section ?

There is no `Reset` in mappings, so I can just omit this suggested mapping (it conflicts with another mapping in human mode). WDYT about keeping just "* `call vimspector#Reset()`"

**Comment by puremourning** [comment]
> There is no Reset in mappings

Ugh, that's weak. I guess i always click Rest button! I'm not even sure it's smart enough to trigger closedown properly if you `:tabclose`.

let's just remove the mapping part for now, and i'll have to add something to the backlog to make this better

**Comment by puremourning** [comment]
Come on bot....

**Comment by puremourning** [comment]
Thanks for the PR!

**Pull request merged**
