### PR TITLE
Add option to skip test programs rebuild

### LINKED ISSUE #645: [Feature Request]: Skip test programs rebuild in run_tests
**Is your feature request related to a problem? Please describe.**

`%SETUP - Building test programs` takes around 15s on my machine every time I want to run the tests, which is a bit annoying if I run just a single test which finishes under a second. That's why any time I work on tests, I just comment the entire block of code.

**Describe the solution you'd like**

Add a flag like `--skip-test-rebuild` and wrap the whole step in an `if`.

**Describe alternatives you've considered**

We could automate it by just testing for existence of one of compiled executables, but it would be breaking change for anyone modifying the test programs.

**Additional context**

### PR DESCRIPTION
**Pull request by dkaszews**
Measured to save 13.5s on Raspberry Pi 4B - nice when running single short test which takes less than that.

Closes #645

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/646)

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/646)* status: all files reviewed, 1 unresolved discussion (waiting on @dkaszews)

___
*[`run_tests` line 50 at r1](https://reviewable.io/reviews/puremourning/vimspector/646#-N92ytCgE1N-NPoEEVuW:-N92ytCh8_XE3tZsz2w1:b53pkec) ([raw file](https://github.com/puremourning/vimspector/blob/16540b8c7929372153fe67d73970ef8c8a588f47/run_tests#L50)):*
> ```
>       shift
>       ;;
>     "--skip-test-build")
> ```

mind if we call it `--skip-build` ? This is the same option that YCM's `run_tests` has so it's easier for me to remember ;)

**Review by dkaszews — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/646)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @puremourning)

___
*[`run_tests` line 50 at r1](https://reviewable.io/reviews/puremourning/vimspector/646#-N92ytCgE1N-NPoEEVuW:-N93-SjJCfu3RT92RYIt:b27hkk6) ([raw file](https://github.com/puremourning/vimspector/blob/16540b8c7929372153fe67d73970ef8c8a588f47/run_tests#L50)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

mind if we call it `--skip-build` ? This is the same option that YCM's `run_tests` has so it's easier for me to remember ;)
</blockquote></details>

Sure, done 😃

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/646#-:-N93-oB9Bl5e_HwZG3dR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dkaszews)

**Pull request merged**
