### PR TITLE
adding support for firefox debugger

### PR DESCRIPTION
**Pull request by dsych**
Basically the title. I felt that it was unfair towards Firefox to only have a debugger for Chrome, especially since Firefox has a really good one, too!

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/457)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/457)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dsych)

___
*[python3/vimspector/gadgets.py, line 362 at r1](https://reviewable.io/reviews/puremourning/vimspector/457#-MjmVLpz3UpTEmalWQAO:-MjmVLpz3UpTEmalWQAP:bhx2i6q) ([raw file](https://github.com/puremourning/vimspector/blob/5f5e612182cec59bcb2bc229baf4bf8333d009a5/python3/vimspector/gadgets.py#L362)):*
> ```Python
>     },
>   },
>   'debugger-for-firefox': {
> ```

Looks like the "proper" name for this is "vscode-firefix-debug" - let's use that. "debugger-for-chrome" is actually the name of the adapter (or was), that's why it's called that.

**Review by puremourning — COMMENTED** [review]
Thanks a lot for this.

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/457#-:-MjoKE8B9KtMWWdAJVhG:b-o34y13)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dsych)

**Review by puremourning — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/457)* status: all files reviewed, 1 unresolved discussion (waiting on @dsych)

**Review by dsych — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/457)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @puremourning)

___
*[python3/vimspector/gadgets.py, line 362 at r1](https://reviewable.io/reviews/puremourning/vimspector/457#-MjmVLpz3UpTEmalWQAO:-Mjr1TIQ-qw0S7KHIiW-:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/5f5e612182cec59bcb2bc229baf4bf8333d009a5/python3/vimspector/gadgets.py#L362)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Looks like the "proper" name for this is "vscode-firefix-debug" - let's use that. "debugger-for-chrome" is actually the name of the adapter (or was), that's why it's called that.
</blockquote></details>

Done.

**Comment by puremourning** [comment]
I think we need to update the table in the README too

**Review by dsych — COMMENTED** [review]
my bad :D

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/457#-:-Mju2_1z9NcXYBu2j28L:bm579w4)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/457#-:-Mju8jwE7z59jaitBdj5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dsych)

**Pull request merged**
