### PR TITLE
Fixes issue with needed elevated privileges on Windows

### PR DESCRIPTION
**Pull request by lilwayne1556**
I ran into an issue with the installation on Windows where the mklink command was failing due to needing sufficient privileges and was able to fixed it by using a direction junction instead of a directory symbolic link

Installing netcoredbg...
You do not have sufficient privilege to perform this operation.
 - FAILED installing netcoredbg: Command '['cmd.exe', '/c', 'mklink', '/D', 'C:\\Users\\wayneb\\vimfiles\\plugged\\vimspector\\gadgets\\windows\\netcoredbg', 'C:\\Users\\wayneb\\vimfiles\\plugged\\vimspector\\gadgets\\windows\\download\\netcoredbg\\master\\root\\netcoredbg']' returned non-zero exit status 1

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/219)

**Comment by puremourning** [comment]
> using a direction junction instead of a directory symbolic link

I knew there was a reason that I was using a junction. This is a regression, so thanks.

I just changed this because `os.path.islink` doesn't return `True` for junctions. This was leading to another problem that each installation was creating a new junction and not removing the old one.

**Comment by lilwayne1556** [comment]
I typically don't like using exceptions for programming logic but python has os.readlink which will return the link path or throw an OSError if it isn't a link. This should work on both Windows & Linux

**Comment by lilwayne1556** [comment]
I think I messed a few things up with that commit, let me fix that

**Comment by lilwayne1556** [comment]
I have Python 3.8.5 installed and it works

**Comment by puremourning** [comment]
> I have Python 3.8.5 installed and it works

hmm interesting. does that mean it doesn't work in python 3.7 ?

**Comment by puremourning** [comment]
ok I tried with python 3.7:

```
C:\Users\ben\vimfiles\bundle\vimspector-Clean>python install_gadget.py --enable-c
Installing vscode-cpptools@0.27.0...
Checksum matches for C:\Users\ben\vimfiles\bundle\vimspector-Clean\gadgets\windows\download\vscode-cpptools\0.27.0\cpptools-win32.vsix, using it
Extracting C:\Users\ben\vimfiles\bundle\vimspector-Clean\gadgets\windows\download\vscode-cpptools\0.27.0\cpptools-win32.vsix to C:\Users\ben\vimfiles\bundle\vimspector-Clean\gadgets\windows\download\vscode-cpptools\0.27.0\root
Removing dir C:\Users\ben\vimfiles\bundle\vimspector-Clean\gadgets\windows\download\vscode-cpptools\0.27.0\root
Making executable: C:\Users\ben\vimfiles\bundle\vimspector-Clean\gadgets\windows\download\vscode-cpptools\0.27.0\root\extension\debugAdapters\OpenDebugAD7
Traceback (most recent call last):
  File "python3\vimspector\installer.py", line 466, in InstallGagdet
    gadget[ 'do' ]( name, root, spec )
  File "python3\vimspector\gadgets.py", line 31, in <lambda>
    gadget ),
  File "python3\vimspector\installer.py", line 330, in InstallCppTools
    MakeExtensionSymlink( name, root )
  File "python3\vimspector\installer.py", line 667, in MakeExtensionSymlink
    MakeSymlink( name, os.path.join( root, 'extension' ) ),
  File "python3\vimspector\installer.py", line 674, in MakeSymlink
    RemoveIfExists( os.path.join( in_folder, link ) )
  File "python3\vimspector\installer.py", line 594, in RemoveIfExists
    if IsLink( destination ):
  File "python3\vimspector\installer.py", line 590, in IsLink
    return bool( os.readlink( destination ) )
ValueError: not a symbolic link
 - FAILED installing vscode-cpptools: not a symbolic link
Failed to install adapters:
 * vscode-cpptools

C:\Users\ben\vimfiles\bundle\vimspector-Clean>
```

**Comment by puremourning** [comment]
maybe it should be just `if not os.path.isdir( ... ) ` ?

**Comment by puremourning** [comment]
OK.i have a solution.

In the pythonic way of "easier to ask forgiveness than permission":

```
  try:
    os.remove( destination )
    Print( "Removed file {}".format( destination ) )
    return
  except OSError:
    pass
```

This works on both windows and MacOS, so probably works on linux too.

**Comment by puremourning** [comment]
Thanks for making a PR !

**Pull request closed without merging**
