### PR TITLE
Make SSH command configurable for remote debug

### PR DESCRIPTION
**Pull request by leszekgrzegorek**
Allow to specify custom SSH command for remote debug, e.g. prepend ssh call with sshpass, etc.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/804)

**Review by puremourning — CHANGES_REQUESTED** [review]
Thanks for sending a PR!

I've avoided this so far on the basis that it is better to use public key authentication. While I have no particular objection to this, what's your specific use case?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/804#-:-NflUmnS6TRSMYlT9F00:bs8r52y)* status: all files reviewed, 2 unresolved discussions (waiting on @leszekgrzegorek)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/804#-NflVAzBDt5yr7lbtc8L:-NflVAzBDt5yr7lbtc8M:bdtoerr) (no related file):*
Need to update:

* docs/configuration.md
* docs/schema/vimspector.schema.json

___
___
*[`python3/vimspector/debug_session.py` line 1662 at r1](https://reviewable.io/reviews/puremourning/vimspector/804#-NflTiIB5kIMvYqzVpRC:-NflTiIB5kIMvYqzVpRD:b-brikfh) ([raw file](https://github.com/puremourning/vimspector/blob/7e1ee2a2548ef34b1942bbd70f1c8074540dd3e5/python3/vimspector/debug_session.py#L1662)):*
> ```Python
> 
>   def _GetSSHCommand( self, remote ):
>     ssh = remote.get( 'ssh', {} ).get( 'cmd', [ 'ssh' ]) + remote.get( 'ssh', {} ).get( 'args', [] )
> ```

I would rather pull out 'ssh' once:

```python
ssh_config = remote.get( 'ssh', {} )
ssh = ssh_config.get( 'cmd', [ 'ssh' ] ) + ssh_config.get( 'args', [] )
```

**Review by leszekgrzegorek — COMMENTED** [review]
Hi, thanks for getting back. In particular, I use it with sshpass without the hassle of uploading keys as my debug environment is disposable. I also think it'd be helpful to use any ssh client / in any location / etc. without making all the shenanigans beneath to use it. Of course, this approach is optional (ssh by default) but as far as we have customized arguments, imo it'd also be good to have the command itself :)

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/804#-:-NfpGu_Q-2F2uveqij1z:bykifaf)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/804#-NflVAzBDt5yr7lbtc8L:-NfpIhG-21QLdPznMHUH:bmaem56) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Need to update:

* docs/configuration.md
* docs/schema/vimspector.schema.json
</blockquote></details>

I'll also update docs and schema.

___

**Comment by leszekgrzegorek** [comment]
*[`python3/vimspector/debug_session.py` line 1662 at r1](https://reviewable.io/reviews/puremourning/vimspector/804#-NflTiIB5kIMvYqzVpRC:-NfpJUjHEntDU_rr5U3y:b-a37jg9) ([raw file](https://github.com/puremourning/vimspector/blob/7e1ee2a2548ef34b1942bbd70f1c8074540dd3e5/python3/vimspector/debug_session.py#L1662)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I would rather pull out 'ssh' once:

```python
ssh_config = remote.get( 'ssh', {} )
ssh = ssh_config.get( 'cmd', [] ) + ssh_config.get( 'args', [] )
```
</blockquote></details>

Agree. It seems you missed 'ssh' in case cmd is not specified (make ssh default).



_Code snippet:_
```Python
ssh_config = remote.get( 'ssh', {} )
ssh = ssh_config.get( 'cmd', [ 'ssh' ] ) + ssh_config.get( 'args', [] )
```

**Review by puremourning — APPROVED** [review]
:lgtm:

Dzękuje bardzo!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/804#-:-NfpnnScEn3gmaRIv7fp:b-bsynf2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @leszekgrzegorek)

**Pull request merged**
