### PR TITLE
Docker workdir support

### PR DESCRIPTION
**Pull request by jordanpwalsh**
This adds an additional optional parameter to the "remote" configuration allowing the working directory to be set during invocation of docker exec. I was originally working around needing to execute the runCommand in an appropriate working directory by running a shell script but thought an option in the config would be beneficial to prevent needing to add those scripts to the source repository. 

Testing output:

Relevant config:
```javascript
"launch": {
	"remote": {
		"container": "${ContainerID}",
		"workdir": "/opt/app-root/src/pyluglite",
		"runCommand": ["pwd"]
	},
...
``` 

Output:
```
 /opt/app-root/src/pyluglite
```

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/819)

**Comment by jordanpwalsh** [comment]
Closing due to accidental code reformatting.

**Comment by jordanpwalsh** [comment]
Re-opened with the file not completely reformatted.

**Comment by puremourning** [comment]
Thanks for sending a PR but I fear this might be a slippery slope to implementing the entire compose file specification, or at least every argument to docker exec. I would prefer either:

- just use simple command and run docker exec manually
- add a docker_args or something akin to the ssh_args or whatever we already have.

**Comment by jordanpwalsh** [comment]
If you prefer, I can implement your option 2 instead; I personally prefer that over a custom command. I would like to push back a little though. I can see your point about not wanting to implement a bunch of the compose  spec, but I’d argue this isn’t quite that. The docker exec options are quite small — user id, env vars, and working directory — and I could easily see the other two being something to include as well. Working directory is just the one I happened to need at the time.

**Comment by puremourning** [comment]
That's sort of my point. It's a bit whack-a-mole. I'd rather have option 2 which is just a list of additional args passed to docker exec. Then I never have to change it again if/when docker or podman inevitably change or add something.

**Comment by jordanpwalsh** [comment]
Sounds good. I’ll update the PR. On Dec 22, 2023, at 5:58 PM, Ben Jackson ***@***.***> wrote:﻿
That's sort of my point. It's a bit whack-a-mole. I'd rather have option 2 which is just a list of additional args passed to docker exec. Then I never have to change it again if/when docker or podman inevitably change or add something.

**Comment by jordanpwalsh** [comment]
I updated the branch per your feedback. I thought a format like below would be more intuitive, but opted to use docker_args from your original suggestion so existing configs aren't broken. 

What I wanted:
```
"container": {
    "name": "string",
    "args": ["string", "string"]
}
``` 

What I did:
```
{
    "container": "string"
    "docker_args": ["string", "string"]
}

**Review by puremourning — COMMENTED** [review]
I think what you wanted was fine, and probably better. We could have doe that with a "if it's an object, then ... else ..." but this is also ok.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/819#-:-NnB3Owk3AIxq9-ta7JT:bcbydi6)* status: 0 of 2 files reviewed, all discussions resolved

**Review by puremourning — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/819)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jordanpwalsh)

**Comment by jordanpwalsh** [comment]
@puremourning I fixed the couple linter complaints. Anything needing to be done about the failing test? Looks like the mac os test failing has been an ongoing thing.

**Comment by puremourning** [comment]
I've kicked the CI. Fingers crossed 🤞

**Comment by puremourning** [comment]
Looks like a lint issue

**Comment by jordanpwalsh** [comment]
@puremourning I don't have your flake8 config and no errors on my end, but I think I found what it was complaining about and fixed it.

**Review by jordanpwalsh — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/819)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jordanpwalsh)

**Comment by puremourning** [comment]
@mergifyio rebase

**Review by puremourning — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/819)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jordanpwalsh)

**Pull request merged**
