### PR TITLE
Add a pre-launch building strategy proposal to the docs

### PR DESCRIPTION
**Pull request by jclsn**

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/740)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/740)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jclsn)

___
*[`README.md` line 2345 at r1](https://reviewable.io/reviews/puremourning/vimspector/740#-NRlq_r65Anu0JaQoJ7O:-NRlq_r65Anu0JaQoJ7P:b-vp9f25) ([raw file](https://github.com/puremourning/vimspector/blob/24058ed563eb49b00c922b6dfbfcb5297ae0baab/README.md#L2345)):*
> ```Markdown
> ## Pre-launch building strategies
> In many cases you will want to rebuild your project before starting a new debugging
> session. Unfortunately Vimspector is not a task manager and implementing this functionality
> ```

I don't see this as "unfortunate" per se.
___
*[`README.md` line 2370 at r1](https://reviewable.io/reviews/puremourning/vimspector/740#-NRlrScw8qynb4Ta9y28:-NRlrScw8qynb4Ta9y29:bjnqbd9) ([raw file](https://github.com/puremourning/vimspector/blob/24058ed563eb49b00c922b6dfbfcb5297ae0baab/README.md#L2370)):*
> ```Markdown
> ```Vim
> " Create a custom debug commmand
> command! Debug call BuildAndDebug()
> ```

use s:BuildAndDebug() (and name the function `s:BuildAndDebug()`, rather than defining a global function?
___
*[`README.md` line 2376 at r1](https://reviewable.io/reviews/puremourning/vimspector/740#-NRlrbZA71LWHXe3YZVw:-NRlrbZA71LWHXe3YZVx:ba86528) ([raw file](https://github.com/puremourning/vimspector/blob/24058ed563eb49b00c922b6dfbfcb5297ae0baab/README.md#L2376)):*
> ```Markdown
> 	:Make
> 	:cclose
> 	autocmd QuickFixCmdPost make ++once call vimspector#Launch()
> ```

I guess this doesn't solve the "if the build fails don't do it" part?

Perhaps it should only call Launch if there are no "errors" detected in the quick fix list? something like `len( filter( getqflist(), 'v:val.valid' ) )`

or perhaps vim-dispatch has a way to determine if the command exited with 0
___
*[`README.md` line 2384 at r1](https://reviewable.io/reviews/puremourning/vimspector/740#-NRlr9YI99okludhv7v-:-NRlr9YI99okludhv7v0:b3a2rdh) ([raw file](https://github.com/puremourning/vimspector/blob/24058ed563eb49b00c922b6dfbfcb5297ae0baab/README.md#L2384)):*
> ```Markdown
> ```
> 
> Now you can just press F12 to rebuild and debug.
> ```

F12 is mapped to `step out` by the default "human mode" mappings. I'm not sure we should be recommending F12, though I admit it's only an example, people will often simply copy/paste

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/740)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jclsn)

___
*[`doc/vimspector.txt` line 98 at r1](https://reviewable.io/reviews/puremourning/vimspector/740#-NRlu4oFC6b1V_HCzM7O:-NRlu4oFC6b1V_HCzM7P:b-hty82s) ([raw file](https://github.com/puremourning/vimspector/blob/24058ed563eb49b00c922b6dfbfcb5297ae0baab/doc/vimspector.txt#L98)):*
> ```help
>   4. Changing the terminal size             |vimspector-changing-terminal-size|
>   5. Custom mappings while debugging |vimspector-custom-mappings-while-debugging|
>   6. Pre-launch building strategies  vimspector-pre-launch-building-strategies
> ```

FYI, this file is automatically generated by a bot from the README so you don't need to update it  manually.

You can update locally with `make vim-docs`

**Review by puremourning — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/740)* status: all files reviewed, 4 unresolved discussions (waiting on @jclsn)

**Comment by puremourning** [comment]
Just need to resolve the conflicts.

**Comment by jclsn** [comment]
I am not really sure what I am supposed to do here. I am only familiar with Gitlab merge conflicts resolving.

**Review by jclsn — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/740)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jclsn)

**Pull request merged**
