### PR TITLE
Update vscode-cpptools from 0.27.0 to 1.6.0

### PR DESCRIPTION
**Pull request by seezer**
Only tested on linux as i don't have any other.

The "newly" introduced _bin_ sub directory was there on windows all the time so i hope this works on osx too.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/449)

**Comment by puremourning** [comment]
Thanks! Let’s  see what CI says.

**Comment by seezer** [comment]
Hmm linux CI fail looks like there's just additional things reported now.
Mac seems off - for what i can see from only the logs...
I'd happily look into linux test cases - haven't noticed any issues using it for a few days with gdb.
For Mac i don't know if i manage to with only the CI bot.

I'll give it a try and also see if i can find vscode-cpptools changelog entries that reflect what we see here.
But it might take a while.

**Comment by puremourning** [comment]
I use Mac primarily so I can check that if fixing the Linux errors doesn’t also fix on Mac.

**Comment by seezer** [comment]
While fixing the linux tests locally, I also got the same errors the CI reported on mac in [build](https://github.com/puremourning/vimspector/actions/runs/1212947357)

```
2 FAILED:
Found errors in /home/seezer/dev/src/vimspector/tests/variables.test.vim:Test_EvaluateFailure():
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_EvaluateFailure[1]..<SNR>20_StartDebugging[16]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[4]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>19 line 1: Current buffer: Expected '/home/seezer/dev/src/vimspector/support/test/python/simple_python/main.py' but got '/home/seezer/dev/src/vimspector/tests/vimspector.Console'
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_EvaluateFailure[1]..<SNR>20_StartDebugging[16]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[9]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>20 line 1: Current line: Expected 23 but got 1
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_EvaluateFailure[5]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>21[1]..AssertMatchList line 1: Expected 3 but got 1
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_EvaluateFailure[5]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>21[1]..AssertMatchList line 5: Pattern 'Watches: ----' does not match ''
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_EvaluateFailure[21]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>22 line 1: Expected ['NameError: name ''test'' is not defined'] but got ['']
Found errors in /home/seezer/dev/src/vimspector/tests/variables.test.vim:Test_SimpleWatches():
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_SimpleWatches[1]..<SNR>20_StartDebugging[16]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[4]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>148 line 1: Current buffer: Expected '/home/seezer/dev/src/vimspector/support/test/python/simple_python/main.py' but got '/home/seezer/dev/src/vimspector/tests/vimspector.Console'
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_SimpleWatches[1]..<SNR>20_StartDebugging[16]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[9]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>149 line 1: Current line: Expected 23 but got 1
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_SimpleWatches[4]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[4]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>151 line 1: Current buffer: Expected '/home/seezer/dev/src/vimspector/support/test/python/simple_python/main.py' but got '/home/seezer/dev/src/vimspector/tests/vimspector.Console'
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_SimpleWatches[4]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[9]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>152 line 1: Current line: Expected 25 but got 1
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_SimpleWatches[9]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[4]..WaitForAssert[2]..<SNR>25_WaitForCommon[15]..<lambda>154 line 1: Current buffer: Expected '/home/seezer/dev/src/vimspector/support/test/python/simple_python/main.py' but got '/home/seezer/dev/src/vimspector/tests/vimspector.Console'
command line..script /home/seezer/dev/src/vimspector/tests/lib/run_test.vim[376]..function RunTheTest[69]..Test_SimpleWatches[9]..vimspector#test#signs#AssertCursorIsAtLineInBuffer[9]..WaitForAssert[2]..<SNR>25_WaitForCommon[40]..Abort line 5: Test timed out!!!
Test caused Vim to exit: Test_SimpleWatches()
%END
Done running tests
```

That was seemingly caused by a invalid debugpy installation. I wrongly ran `run_tests` with `--install` after already having all gadgets installed and CTRL+C'ed it after vscode-tools.
After running test once more with a clean `--install` everything worked:

```
From /home/seezer/dev/src/vimspector/tests/variables.test.vim:
Executing Test_EvaluateConsole()
Executing Test_EvaluateFailure()
Executing Test_EvaluateInput()
Executing Test_EvaluatePromptConsole()
Executing Test_ExpandVariables()
Executing Test_ExpandWatch()
Executing Test_SetVariableValue_Balloon()
Executing Test_SetVariableValue_Local()
Executing Test_SetVariableValue_Watch()
Executing Test_SimpleWatches()
Executing Test_VariableEval()
Executing Test_VariableEvalExpand()
Executed 12 tests
%END
Done running tests
```

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/449#-:-Mj6GdoK3zfsdicmzJRT:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @seezer)

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/449#-:-Mj6HVXPAuddIw7aXBPI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @seezer)

**Pull request merged**
