### PR TITLE
Custom text of Winbar buttons.

### PR DESCRIPTION
**Pull request by roachsinai**
Add an example to show symbol and mapping on WinBar:

image

UI test result:

image

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/221)

**Comment by roachsinai** [comment]
Yeah, got it. I though still pass the layout check.

I should check what I changed!

**Comment by puremourning** [comment]
> I should check what I changed!

👍

**Comment by roachsinai** [comment]
@puremourning done. Thanks for this instruction about how to test your code.

**Comment by puremourning** [comment]
Thanks, can you rebase on master and squash the commits ?

**Comment by puremourning** [comment]
Actually, the bot will rebase it for you. Good bot.

**Comment by roachsinai** [comment]
So I don't need to do anything?

**Comment by roachsinai** [comment]
What a eye-opener day!

**Pull request merged**
