### PR TITLE
Add tests for c# using netcoredbg

### PR DESCRIPTION
**Pull request by puremourning**
Update netcoredbg to latest version to fix macOS brokenness.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/386)

**Comment by puremourning** [comment]
cc @Anvba @aqez

**Comment by aqez** [comment]
I think this is a great move! I was curious if the the mono debug was just me. The tests will definitely be a big improvement too for people without all of the supported platforms available

**Comment by puremourning** [comment]
Unfortunately it seems that netcoredbg isn't working in the CI:

```
2021-04-15 20:49:19,822 - DEBUG - Message received: {'seq': 7, 'command': 'configurationDone', 'message': "Failed command 'configurationDone' : 0x80131c3c", 'request_seq': 4, 'success': False, 'type': 'response'}
2021-04-15 20:49:19,823 - ERROR - Request failed: Failed command 'configurationDone' : 0x80131c3c
```

@viewizard any idea what this status code means? `0x80131c3c`. Trying to run netcoredbg in my CI, but it's failing on macOS with that error. I will try and get the netcoredbglog, but it's tricky with CI.

**Comment by viewizard** [comment]
<HRESULT NumericValue="0x80131c3c">
  <SymbolicName>CORDBG_E_DEBUG_COMPONENT_MISSING</SymbolicName>
  <Message>"A debug component is not installed."</Message>
  <Comment>A debug component is not installed</Comment>
</HRESULT>

**Comment by puremourning** [comment]
Looks like maybe fixed in botnet 5?

https://github.com/dotnet/runtime/pull/42900
https://github.com/dotnet/runtime/issues/42888

I'll try

**Comment by puremourning** [comment]
Nope, no difference.

**Comment by puremourning** [comment]
I found a workaround. Seems there is a bug in the dbgshim fixed in a later .net core? https://github.com/dotnet/runtime/issues/42311#issuecomment-738857792

Anyway, I switched my CI to using Xcode 11 and it seems to work again.

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/386#-:-MYMZcbB0VT-AZnFSveF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @puremourning)

**Comment by puremourning** [comment]
@viewizard according to [this post](https://github.com/dotnet/runtime/pull/44748#issuecomment-728924775), it looks like MS are recommending that the latest dbgshim be shipped with the debugger. Would it be possible for netcoredbg to ship a later libdbgshim.dylib to avoid this issue? Not a big deal if not.

**Comment by viewizard** [comment]
But we add dbgshim into debugger package (Windows/Linux/macOS). It copy from .Net SDK installed on build system. Not sure about .Net SDK that have travis CI.

**Comment by viewizard** [comment]
https://travis-ci.org/github/Samsung/netcoredbg/jobs/766946971 it install 
```
dotnet-install: Calling: get_specific_version_from_version https://dotnetcli.azureedge.net/dotnet 3.1 x64 Latest 
...
dotnet-install: Constructed legacy named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.408/dotnet-dev-osx-x64.3.1.408.tar.gz
```
looks like it install latest .Net SDK 3.1

**Comment by viewizard** [comment]
Wait, this is our script hardcoded tp install 3.1 for now. =)

**Pull request merged**
