### PR TITLE
Fix duplicate environment variables

### PR DESCRIPTION
**Pull request by zoumi**
Fix https://github.com/puremourning/vimspector/issues/310

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/311)

**Comment by puremourning** [comment]
Thanks. Do you think we should just never copy the whole environment? Seems a bit wasteful anyway. IMO this is still a cpptools bug - the environment that we send is still _valid_. Though a few users have hit this now so thanks for the workaround.

**Comment by zoumi** [comment]
Sorry, I'm not familiar with linux environment variables, so I test the OS name in my Code and test the code on my PC.
I think we don't need copy the environment variables  if you think it's OK to do so in linux.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/311)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @zoumi)

___
*[python3/vimspector/debug_session.py, line 746 at r1](https://reviewable.io/reviews/puremourning/vimspector/311#-MNZhL4L2_cryCZH4O7R:-MNZhL4L2_cryCZH4O7S:b-dsotya) ([raw file](https://github.com/puremourning/vimspector/blob/b111e45bf5a5f94cd5a27a4a68f143d9909fdd79/python3/vimspector/debug_session.py#L746)):*
> ```Python
>     env = os.environ.copy()
>     if os.name == "nt":
>         env = {}
> ```

please fix lint error

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/311)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @zoumi)

___
*[python3/vimspector/debug_session.py, line 744 at r1](https://reviewable.io/reviews/puremourning/vimspector/311#-MNZh_YjEQRE5KHCSpM-:-MNZh_YjEQRE5KHCSpM0:b-xw8riv) ([raw file](https://github.com/puremourning/vimspector/blob/b111e45bf5a5f94cd5a27a4a68f143d9909fdd79/python3/vimspector/debug_session.py#L744)):*
> ```Python
> 
>     # TODO: Do we actually need to copy and update or does Vim do that?
>     env = os.environ.copy()
> ```

we should skip this copy if we're not going to use it

**Comment by zoumi** [comment]
@puremourning Sorry, I can't sign in reviewable.io. 
May I close this request then you make a new request instead?

**Comment by puremourning** [comment]
Thanks for this, I've pushed a similar patch #315 - can you try it?

**Pull request closed without merging**
