### PR TITLE
add example for testing typescript code with vscode-js-debug

### PR DESCRIPTION
**Pull request by xddq**
Adding an example for debugging a typescript application using vimspector and
vscode-js-debug. Typescript is a great language, but sadly the setup is hell.
Debugging is no exception to this. This PR tries adding what would have been very beneficial for
me when checking out vimspector for debugging typescript code. It contains a step by step description which can be followed by 'anyone'.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/817)

**Review by puremourning — CHANGES_REQUESTED** [review]
Thanks for sending a PR!

It's always good to improve our community-supported docs.

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/817#-:-NmBivOKEqOGQ7wcAPa_:b-6twb6i)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @xddq)

___
*[`support/test/node/typescript/.vimspector.json` line 6 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBgCJ_9SMiVKlMo1iY:-NmBgCJ_9SMiVKlMo1iZ:b-n4djdh) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/.vimspector.json#L6)):*
> ```JSON
>       "adapter": "js-debug",
>       "configuration": {
>         "request": "attach",
> ```

Seems odd to use 'attach' here. Don't we want a "launch" configuration?

this is what I've always done for typescript projects (same for both the old vscode-node and new js-debug):

```
{
  "configurations": {
    "run": {
      "adapter": "js-debug",
      "configuration": {
        "request": "launch",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "program": "${workspaceRoot}/dist/index.js",
        "cwd": "${workspaceRoot}",
        "type": "pwa-node"
      }
    }
  }
}
```

TBH I don't think we should be "recommending" a sort of hacky workaround.
___
*[`support/test/node/typescript/package.json` line 2 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBhIv45gkNOul3Oq2y:-NmBhIv45gkNOul3Oq2z:bc93dod) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/package.json#L2)):*
> ```JSON
> {
>   "name": "vimspector-typescript",
> ```

include the word "example" or "test" or something?
___
*[`support/test/node/typescript/README.md` line 3 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBhPWX6Pezztu2W_63:-NmBhPWX6Pezztu2W_64:bpw7l7r) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L3)):*
> ```Markdown
> # Howto
> 
> Typescript is a great language (looking past dependency hells of the js
> ```

thanks for writing all this up! 

This first sentence is essentially expressing an opinion and is sort of tangential to the purpose of the guide. I don't really want to participate in any language fetish wars, or at least, not in print! So, I think we can just remove this first sentence.
___
*[`support/test/node/typescript/README.md` line 7 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBiWmzA48RFLYTDfv-:-NmBiWmzA48RFLYTDfv0:b-ls743h) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L7)):*
> ```Markdown
> how to use vimspector with
> [vscode-js-debug](https://github.com/microsoft/vscode-js-debug). I only could
> make this combination work by using 'attach' as launch. This is the reason why
> ```

Launch certainly works. I've done it myself. Given that, would it be better to just enhance the main README's typescript config area? The benefits of that:

1. It appears in :help vimspector
2. Only one place to update when things inevitably change again for pointless annoying reasons (!)
3. Only one place for people to look
4. appears on front page of GitHub project.

WDYT?
___
*[`support/test/node/typescript/README.md` line 8 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBi1dwC3r6gR4MsNNG:-NmBi1dwC3r6gR4MsNNH:bb8t6tn) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L8)):*
> ```Markdown
> [vscode-js-debug](https://github.com/microsoft/vscode-js-debug). I only could
> make this combination work by using 'attach' as launch. This is the reason why
> this guide will explain how to use it with 'attach'. For all available options
> ```

The main README should probably use this link instead. We have a section on configuration for typescript there.
___
*[`support/test/node/typescript/README.md` line 13 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBiMBQ21Zoa-WGDE1I:-NmBiMBQ21Zoa-WGDE1J:bsy0ox1) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L13)):*
> ```Markdown
> ## Prerequisites
> 
> - Ensure you are using nodejs version 18 or 20 (was tested with these and these are
> ```

Is this a requirement of this example, or of js-debug in general?
___
*[`support/test/node/typescript/README.md` line 21 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBi6mI18wLxWR3OW9i:-NmBi6mI18wLxWR3OW9j:bde10zx) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L21)):*
> ```Markdown
> ## Debugging
> 
> - Build the project `yarn build`
> ```

do we _really_ need to depend on _yarn_ for this trivial example? Can we not just run tsc ?

**Review by xddq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/817)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @puremourning)

___
*[`support/test/node/typescript/.vimspector.json` line 6 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBgCJ_9SMiVKlMo1iY:-NmDa6dh1wPTPt7M9ex3:bdinomt) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/.vimspector.json#L6)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Seems odd to use 'attach' here. Don't we want a "launch" configuration?

this is what I've always done for typescript projects (same for both the old vscode-node and new js-debug):

```
{
  "configurations": {
    "run": {
      "adapter": "js-debug",
      "configuration": {
        "request": "launch",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "program": "${workspaceRoot}/dist/index.js",
        "cwd": "${workspaceRoot}",
        "type": "pwa-node"
      }
    }
  }
}
```

TBH I don't think we should be "recommending" a sort of hacky workaround.
</blockquote></details>

Good point, got it working with 'launch' now. Your config seems to me like it is used for debugging the "compiled/transpiled" js, I will adapt the config to use launch and still debug the typescript code.

FYI: never used reviewable before, so sorry in advance if I mess stuff up here.
___
*[`support/test/node/typescript/package.json` line 2 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBhIv45gkNOul3Oq2y:-NmDctBW-zipJHV91P15:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/package.json#L2)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

include the word "example" or "test" or something?
</blockquote></details>

Done.
___
*[`support/test/node/typescript/README.md` line 3 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBhPWX6Pezztu2W_63:-NmDcuuD0GwXKfg9NXvY:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L3)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

thanks for writing all this up! 

This first sentence is essentially expressing an opinion and is sort of tangential to the purpose of the guide. I don't really want to participate in any language fetish wars, or at least, not in print! So, I think we can just remove this first sentence.
</blockquote></details>

Done.
___
*[`support/test/node/typescript/README.md` line 7 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBiWmzA48RFLYTDfv-:-NmDeWLn4g9-DyHqrQUu:bfiunev) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L7)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Launch certainly works. I've done it myself. Given that, would it be better to just enhance the main README's typescript config area? The benefits of that:

1. It appears in :help vimspector
2. Only one place to update when things inevitably change again for pointless annoying reasons (!)
3. Only one place for people to look
4. appears on front page of GitHub project.

WDYT?
</blockquote></details>

Sounds good, I gave it a shot. Let me know what you think. I would still keep this readme here to make it easy for people checking out the example.
___
*[`support/test/node/typescript/README.md` line 8 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBi1dwC3r6gR4MsNNG:-NmDi2zgE0ro0lhz2V0Q:b-3b2237) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L8)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

The main README should probably use this link instead. We have a section on configuration for typescript there.
</blockquote></details>

It is in the main readme as well. I think having duplication here is fine so that you can go through the example only with the readme within it. Could also remove it if you want to. I would rather not.
___
*[`support/test/node/typescript/README.md` line 13 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBiMBQ21Zoa-WGDE1I:-NmDcwUK7-41paNaM4UO:b-uqvjir) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L13)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Is this a requirement of this example, or of js-debug in general?
</blockquote></details>

I meant that I tested it with these versions. I checked vscode-js-debug repo and did not find a mention of a node version so I am not sure which is the min supported one. 
___
*[`support/test/node/typescript/README.md` line 21 at r2](https://reviewable.io/reviews/puremourning/vimspector/817#-NmBi6mI18wLxWR3OW9i:-NmDdjyJCI7ydtVJcdNG:bq706it) ([raw file](https://github.com/puremourning/vimspector/blob/5d4a94dff1bd7b54dc098737db33a5aefdb67749/support/test/node/typescript/README.md#L21)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

do we _really_ need to depend on _yarn_ for this trivial example? Can we not just run tsc ?
</blockquote></details>

No. Will use the default that comes with node which is npm.

**Review by puremourning — CHANGES_REQUESTED** [review]
thanks again

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/817#-:-NnB3GpJ2rtH7aCQZesV:b4tufv2)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @xddq)

___
*[`README.md` line 2155 at r4](https://reviewable.io/reviews/puremourning/vimspector/817#-NnB2kY80swo0_5aZDKL:-NnB2kY80swo0_5aZDKM:befytbx) ([raw file](https://github.com/puremourning/vimspector/blob/04754e816dfcb144286e1cda862bbbc499a197d1/README.md#L2155)):*
> ```Markdown
> the documentation [here](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md).
> 
> To install vscode-js-debug, run `install_gadget.py --force-enable-node`. There
> ```

or `VimspectorInstall vscode-js-debug`
___
*[`README.md` line 2174 at r4](https://reviewable.io/reviews/puremourning/vimspector/817#-NnB2bm4ABhX4paMvUx8:-NnB2bm4ABhX4paMvUx9:be4lpls) ([raw file](https://github.com/puremourning/vimspector/blob/04754e816dfcb144286e1cda862bbbc499a197d1/README.md#L2174)):*
> ```Markdown
>         "type": "pwa-node"
>       },
>       "breakpoints": {
> ```

I don't think we should include this here, as it's a preference. Feel free to comment it out with a note that it's one way to configure the exception breakpoints.
___
*[`support/test/node/typescript/package-lock.json` line 1 at r4](https://reviewable.io/reviews/puremourning/vimspector/817#-NnB2DB8BgVjovuHl9Jc:-NnB2DB8BgVjovuHl9Jd:b-4h8mu1) ([raw file](https://github.com/puremourning/vimspector/blob/04754e816dfcb144286e1cda862bbbc499a197d1/support/test/node/typescript/package-lock.json#L1)):*
> ```JSON
> {
> ```

do we need this file? I don't like these lock file littering up the place particularly and for something this trivial, I really don't care about it's purported purpose.

**Review by puremourning — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/817)* status: all files reviewed, 3 unresolved discussions (waiting on @xddq)

**Review by xddq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/817)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @puremourning)

___
*[`README.md` line 2155 at r4](https://reviewable.io/reviews/puremourning/vimspector/817#-NnB2kY80swo0_5aZDKL:-No10vRb8BPwumETv6m3:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/04754e816dfcb144286e1cda862bbbc499a197d1/README.md#L2155)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

or `VimspectorInstall vscode-js-debug`
</blockquote></details>

Done.
___
*[`README.md` line 2174 at r4](https://reviewable.io/reviews/puremourning/vimspector/817#-NnB2bm4ABhX4paMvUx8:-No10xqH9qjl2jBwuo55:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/04754e816dfcb144286e1cda862bbbc499a197d1/README.md#L2174)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I don't think we should include this here, as it's a preference. Feel free to comment it out with a note that it's one way to configure the exception breakpoints.
</blockquote></details>

Done.
___
*[`support/test/node/typescript/package-lock.json` line 1 at r4](https://reviewable.io/reviews/puremourning/vimspector/817#-NnB2DB8BgVjovuHl9Jc:-No12MT-9ieb6j2Ucdxh:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/04754e816dfcb144286e1cda862bbbc499a197d1/support/test/node/typescript/package-lock.json#L1)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

do we need this file? I don't like these lock file littering up the place particularly and for something this trivial, I really don't care about it's purported purpose.
</blockquote></details>

Done.

**Comment by xddq** [comment]
@puremourning Any updates on this? I went through your suggestions and made the changes accordingly

**Review by puremourning — APPROVED** [review]
:lgtm:

@mergifyio rebase

> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/817#-:-NxCbj4aA2DbVkVJwF1L:b-7xb5cy)* status: all files reviewed, 1 unresolved discussion (waiting on @xddq)

**Pull request merged**
