### PR TITLE
Add a runnable Go example

### PR DESCRIPTION
**Pull request by simondrake**

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/420)

**Review by puremourning — COMMENTED** [review]
Am I missing something ... should there be a .vimspector.json included with this ?

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/420#-:-McyLdtZ5_wQUPrYBC_P:b2bey0y)* status: 0 of 6 files reviewed, all discussions resolved

**Comment by simondrake** [comment]
Woops - I have a global gitignore for the vimspector debug configs, and didn't realise I hadn't added it. It's there now.

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks !

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/420#-:-McyMoXk7wmmRO9J73ca:b4p606z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @simondrake)

**Pull request merged**
