### PR TITLE
Update netcoredbg to 1.2.0-738 to support async/await

### PR DESCRIPTION
**Pull request by aqez**
Simple pull to update netcoredbg to 1.2.0-738. 

**There is currently no new binary for macos, so I was hoping that setting 'version' on the macos settings would override the 'all' settings.** Please advise if that is not the case. I do not have a mac to test on.

I have tested on arch linux with kernel 5.11.4-arch1-1 and Windows 10.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/371)

**Comment by puremourning** [comment]
Why is there no macOS release? Can’t we wait until it’s available?

**Comment by puremourning** [comment]
any update on the macOS version?

**Comment by aqez** [comment]
I check back pretty often, but unfortunately no luck yet. Is there anything you would like to do on this PR until an update is available?

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/371#-:-MWBj9-55iKCXllPP1WA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aqez)

**Comment by puremourning** [comment]
let's merge it. if a macOS version turns up we can use it

**Review by puremourning — APPROVED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/371#-:-MWBjRyT1Njlfr_2SmmT:b8b79qu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aqez)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/371)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aqez)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/371#-MWBjW5xEL4MV7uHbo67:-MWBjW5xEL4MV7uHbo68:b-eqjn6m) (no related file):*
let me just test it on macOS actually.

---

**Comment by aqez** [comment]
> :lgtm_cancel:
> 
> > _[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/371#-:-MWBjRyT1Njlfr_2SmmT:b8b79qu)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aqez)

Sounds good, I'll continue to keep an eye out and open another PR when it shows up.

**Review by puremourning — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/371#-:-MWBkEOGDaWRmS4CPEGY:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aqez)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/371#-MWBjW5xEL4MV7uHbo67:-MWBkFO05HtziAzTgS9S:btpoguu) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

let me just test it on macOS actually.
</blockquote></details>

Tested ok, installed the right version on macOS and linux.

---

**Review by puremourning — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/371)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aqez)

**Pull request merged**
