### PR TITLE
docs(README): Fix typos and grammar issues

### PR DESCRIPTION
**Pull request by dzfrias**
Just made some small edits to the README to fix some typos!

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/636)

**Review by puremourning — CHANGES_REQUESTED** [review]
thanks for the PR!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/636#-:-N8EgXvr2CO0_bG9gvUY:bq0olvr)* status: all files reviewed, 3 unresolved discussions (waiting on @dzfrias)

___
*[`README.md` line 291 at r1](https://reviewable.io/reviews/puremourning/vimspector/636#-N8Efqis1AW8d9Gh-6-s:-N8Efqis1AW8d9Gh-6-t:bms0y7n) ([raw file](https://github.com/puremourning/vimspector/blob/d32a308448f664d299c261fd4def7b569653a190/README.md#L291)):*
> ```Markdown
> * Balloons - There is the `<Plug>VimspectorBalloonEval` mapping. There is no
> default mapping for this, so I recommend something like this to get variable
> displays in popups:
> ```

the original was correct, and reads better IMO
___
*[`README.md` line 330 at r1](https://reviewable.io/reviews/puremourning/vimspector/636#-N8EfzTpDzjE7hLdsiRI:-N8EfzTpDzjE7hLdsiRJ:bq3h4p8) ([raw file](https://github.com/puremourning/vimspector/blob/d32a308448f664d299c261fd4def7b569653a190/README.md#L330)):*
> ```Markdown
> which can be used to check if everything is working. This is used by the
> regression tests in CI so it should always work, and is a good way to check if 
> the problem is in your configuration rather than a bug.
> ```

I don't think these changes are necessary. the original is fine. The additional articles don't increase clarity.



_Code quote:_
```Markdown
There's also a C++ project in `tests/testdata/cpp/simple/` with a `Makefile`
which can be used to check if everything is working. This is used by the
regression tests in CI so it should always work, and is a good way to check if
the problem is in your configuration rather than a bug.
```
___
*[`README.md` line 774 at r1](https://reviewable.io/reviews/puremourning/vimspector/636#-N8EgAeDDmdAX9HCrCTG:-N8EgAeDDmdAX9HCrCTH:b20u35m) ([raw file](https://github.com/puremourning/vimspector/blob/d32a308448f664d299c261fd4def7b569653a190/README.md#L774)):*
> ```Markdown
> ```
> 
> You may also wish to add mappings for going up/down the stack, for example:
> ```

I prefer 'moving' or 'navigating' here than 'going'

**Comment by dzfrias** [comment]
I added your requested changes. Do these look good @puremourning?

**Review by puremourning — APPROVED** [review]
LGTM, please can you squash the commits, then we can merge this! Thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/636#-:-N8EyxuS9kNaXrAXJDJY:b-emxafa)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzfrias)

**Comment by dzfrias** [comment]
I squashed them on my fork's branch. The branch already merged though. Is there anything I can do to squash them on puremourning:master?

**Comment by puremourning** [comment]
Nah it's ok don't worry. The merge bot was a bit overzealous. Not a problem.

**Pull request merged**
