### PR TITLE
Allow a gadget to specify a custom extension path

### PR DESCRIPTION
**Pull request by AllanGuigou**
The purpose of this change is to support `kotlin-debug-adapter`.

- Allow a gadget to specify a custom extension path
  When installing a custom gadget not officially supported by vimspector the
  default extension path is 'extension', this works for vscode extensions but
  does not support some debug adapters. This commit gives the ability to change
  that default extension path by specifying 'extension_path' within the gadget
  installer file.
  
  Installing 'cust_adapter' would use the extension path 'adapter' rather
  than 'extension' (ie ${gadgetDir}/cust_adapter/${version}/root/adapter)
  ```
  {
    "cust_adapter": {
      "download": { ... },
      "all": {
        "extension_path": "adapter",
        "adapters": { ... }
      }
    }
  }
  ```

- Add support test for kotlin
  - I saw that ruby had a support test even though it was not a supported language, LMK if this commit should be removed.

Once this is approved, I plan on editing [languages](https://github.com/puremourning/vimspector/wiki/languages) with:

# Kotlin

## Gadget Installer

cust_kotlin-debug-adapter.json
```json
{
  "cust_kotlin-debug-adapter": {
    "download": {
      "url": "https://github.com/fwcd/kotlin-debug-adapter/releases/download/${version}/adapter.zip"
    },
    "all": {
      "version": "0.4.2",
      "file_name": "adapter.zip",
      "checksum": "434abbcc5600fa6d2424930a7c81e4c30ae5fbf05cce1cbb0af96b58db540294",
      "make_executable": [
        "bin/kotlin-debug-adapter"
      ],
      "extension_path": "adapter",
      "adapters": {
        "cust_kotlin-debug-adapter": {
          "command": [
            "${gadgetDir}/cust_kotlin-debug-adapter/bin/kotlin-debug-adapter"
          ],
          "name": "kotlin-debug-adapter",
          "configuration": {
            "projectRoot": "${workspaceRoot}"
          }
        }
      }
    }
  }
}
```

## Vimspector Config

.vimspector.json
```json
{
  "configurations": {
    "kotlin-debug-adapter launch": {
      "adapter": "cust_kotlin-debug-adapter",
      "configuration": {
        "request": "launch",
        "projectRoot": "${workspaceFolder}",
        "mainClass": "vimspector/test/ApplicationKt"
      }
    },
    "kotlin-debug-adapter attach": {
      "adapter": "cust_kotlin-debug-adapter",
      "configuration": {
        "request": "attach",
        "projectRoot": "${workspaceFolder}",
        "hostName": "${hostName}",
        "port": "${port}"
      }
    }
  }
}
```

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/328)

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/328)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @AllanGuigou)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/328#-MPi8h-h1Y_TK0DPNS-m:-MPi8h-h1Y_TK0DPNS-n:b-ehfgt5) (no related file):*
anything in docs/ we need to update ?

---
___
*[support/test/kotlin/gradle/wrapper/gradle-wrapper.jar, line 0 at r1](https://reviewable.io/reviews/puremourning/vimspector/328#-MPi8Lhm92aOpAvmJZBl:-MPi8Lhm92aOpAvmJZBm:b4r3as0) ([raw file](https://github.com/puremourning/vimspector/blob/ec68811c8a598fda979e6d21bc933bb6a31d50c1/support/test/kotlin/gradle/wrapper/gradle-wrapper.jar#L0)):*
This is a bit depressing. I don't feel like it's a great story for every vimspector user to have to download this 58k jar file and for us to store it in the repo.

Maybe we are better off creating a GitHub.com/puremournig/vimspector-samples repo and putting this there?

WDYT ?

**Review by puremourning — COMMENTED** [review]
tried this out. works well. thanks.

:lgtm: 

> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/328#-:-MPsk2Sq2kPbL9kxPcxw:b-v5s50a)* status: all files reviewed, 2 unresolved discussions (waiting on @AllanGuigou)

**Comment by AllanGuigou** [comment]
> > Reviewed 2 of 10 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/328)_ status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @AllanGuigou)
> 
> _[a discussion](https://reviewable.io/reviews/puremourning/vimspector/328#-MPi8h-h1Y_TK0DPNS-m:-MPi8h-h1Y_TK0DPNS-n:b-ehfgt5) (no related file):_
> anything in docs/ we need to update ?

I do think it would be valuable to describe this new behavior in the docs, but I'm a bit unsure where I could make updates. I see the [gadgets schema](https://github.com/puremourning/vimspector/blob/master/docs/schema/gadgets.schema.json), but don't see reference to a gadget installer schema.

> _[support/test/kotlin/gradle/wrapper/gradle-wrapper.jar, line 0 at r1](https://reviewable.io/reviews/puremourning/vimspector/328#-MPi8Lhm92aOpAvmJZBl:-MPi8Lhm92aOpAvmJZBm:b4r3as0) ([raw file](https://github.com/puremourning/vimspector/blob/ec68811c8a598fda979e6d21bc933bb6a31d50c1/support/test/kotlin/gradle/wrapper/gradle-wrapper.jar#L0)):_
> This is a bit depressing. I don't feel like it's a great story for every vimspector user to have to download this 58k jar file and for us to store it in the repo.
> 
> Maybe we are better off creating a GitHub.com/puremournig/vimspector-samples repo and putting this there?
> 
> WDYT ?

Typically kotlin projects include the gradle wrapper, but a local install of gradle will work just fine. I think in this situation it would be acceptable to drop the gradle wrapper.

**Comment by puremourning** [comment]
> acceptable to drop the gradle wrapper

yeah, let's do that :)

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks!

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/328#-:-MQM6P8K3gpzsI9OjkPa:b9benhj)* status: all files reviewed, 2 unresolved discussions (waiting on @AllanGuigou and @puremourning)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/328#-MPi8h-h1Y_TK0DPNS-m:-MQM6S2K0ayjxn4cZj8d:b-f8v7ue) (no related file):*
<details><summary><i>Previously, AllanGuigou (Allan Guigou) wrote…</i></summary><blockquote>

I do think it would be valuable to describe this new behavior in the docs, but I'm a bit unsure where I could make updates. I see the [gadgets schema](https://github.com/puremourning/vimspector/blob/master/docs/schema/gadgets.schema.json), but don't see reference to a gadget installer schema. 
</blockquote></details>

I guess it's just the wiki page then (the gadget installer spec is defined there I think)

---

**Comment by AllanGuigou** [comment]
> I guess it's just the wiki page then (the gadget installer spec is defined there I think)

Update the wiki page with documentation for `extension_path` and support for kotlin. 👍

**Review by puremourning — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/328#-:-MQQsxrG5BN1s2Oak3q-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/328)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
