### PR TITLE
Add lua support through local-lua-debugger-vscode

### PR DESCRIPTION
**Pull request by eduardomezencio**
Add the lua adapter to gadgets.py and installer.py, update the README.md file and create basic tests using lua, luajit and love.

I tested installing the lua debugger with both install_gadget.py and VimspectorInstall and tested debugging in both test cases added to support/test/lua.

I decided to add it as Supported and set `'enabled': False` in `gadgets.py`. If I'm wrong just tell me and I'll change it.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/294)

**Review by puremourning — COMMENTED** [review]
Wow. Thanks so much. This is a top quality PR. Much appreciated. I’ll try and take it for a spin later. But a quick scan it looks pretty much spot on. 

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/294#-:-MMAE8km7PTgx-sSaNdT:b-c5hk6b)* status: 0 of 7 files reviewed, all discussions resolved

**Comment by puremourning** [comment]
Works great 

Screenshot 2020-11-15 at 15 01 10

Thanks so much for this.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/294)* status: all files reviewed, 3 unresolved discussions (waiting on @eduardomezencio)

___
*[README.md, line 147 at r2](https://reviewable.io/reviews/puremourning/vimspector/294#-MMBMetWAJWTJKi308x6:-MMBMetWAJWTJKi308x7:bwwx37z) ([raw file](https://github.com/puremourning/vimspector/blob/1eb2bc2199d5ea83aa64bab849da875938c653f8/README.md#L147)):*
> ```Markdown
> | Javascript         | Supported    | `--force-enable-chrome`          | debugger-for-chrome                | Chrome                                     |
> | Java               | Supported    | `--force-enable-java  `          | vscode-java-debug                  | Compatible LSP plugin (see [later](#java)) |
> | Lua                | Supported    | `--force-enable-lua`             | local-lua-debugger-vscode          | Node, Npm, Lua interpreter                 |
> ```

it's probably best to mark it as `Experimental` for now. I don't use Lua so there's no way I will know if this breaks unless we add a proper regression test (i.e. `tests/language_lua.test.vim`), and even then I'm not likely to be able to provide particularly good support for it as I don't know the first thing about Lua debugging.

that is, unless you fancy volunteering to "own" this integration going forwards :)

I'm thinking about a way to allow these gadget definitions to be provided by other plugins because it's a little unwieldy to have them all centralised. the gadget config file was one attempt at thsat, but it's limited by the way scripts seem to be needed too often. perhaps that's still a way forward, or perhaps I have to find a way to make a stable public API. ugh. anyway, that's for the future I guess.
___
*[README.md, line 1792 at r2](https://reviewable.io/reviews/puremourning/vimspector/294#-MMBMvzv57NzEsJy2q0c:-MMBMvzv57NzEsJy2q0d:bwi4btz) ([raw file](https://github.com/puremourning/vimspector/blob/1eb2bc2199d5ea83aa64bab849da875938c653f8/README.md#L1792)):*
> ```Markdown
> > I created Vimspector because I find changing tools frustrating. `gdb` for c++,
> > `pdb` for python, etc. Each has its own syntax. Each its own lexicon. Each its
> > own foibles.
> ```

just for future reference, please try not to submit unrelated whitespace changes; they are just noise in code reviews. no need to worry about it for this.
___
*[python3/vimspector/gadgets.py, line 503 at r2](https://reviewable.io/reviews/puremourning/vimspector/294#-MMBNCtr4wwB13D_tsbr:-MMBNCtr4wwB13D_tsbs:b-s8kpks) ([raw file](https://github.com/puremourning/vimspector/blob/1eb2bc2199d5ea83aa64bab849da875938c653f8/python3/vimspector/gadgets.py#L503)):*
> ```Python
>     'repo': {
>       'url': 'https://github.com/tomblind/local-lua-debugger-vscode.git',
>       'ref': 'release-0.2.0'
> ```

would `release-${version}` be better here ? Saves having to update it twice.

**Comment by eduardomezencio** [comment]
I'll apply your suggested change in `gadgets.py` and also check into building a proper regression test so that we'll know when it breaks. You can count on me to maintain it when it do. I don't know if I'll be able to write the test properly because I still don't get 100% of what I see on the other test examples. I'll study it and see what I can get.

But yes, for the future, I guess it would be better to maintain all language support separately. I must say one thing I particularly loved about the way things are now is that `:VimspectorInstall` can autocomplete with available adapters to install and `.install_gadget.py` shows all options dynamically in `--help`. It would be nice to have a way to keep this even if each language support plugin is in a separate repository.

**Comment by puremourning** [comment]
For the test something like language_go is a minimal ‘sanity’ test. Just starts a debug seasion and steps a bit. Some of the newer tests are simpler and use more of the public APIs. If you want to chat, the best place is the Gitter room :)

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks!

> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/294#-:-MMHTXE3Dr0NtKon4kiO:b9benhj)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
