### PR TITLE
Delay launching the python interpreter until needed

### LINKED ISSUE #361: Forking Python process on startup causes 120ms slowdown (60ms → 180ms) in Neovim
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug

`autoload/vimspector.vim` forks Python with `:py3` to define a Python function.

This function is not used on startup, which leads to a spurious 120ms slowdown even when opening an empty buffer or a file in a project that doesn't use Vimspector.

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc`?
  * **Yes**
* If you are using Neovim, does your issue reproduce using Vim? \[Yes/No]
  * **No**

> List of steps to reproduce:

```
git clone https://github.com/puremourning/vimspector
cd vimspector
git checkout 11edcddd9c6208d1290c1ff1fc1c598a3b963aca
time nvim -u support/minimal_vimrc +q
```

(observe time, ~180ms)

apply this patch:

```diff
diff --git a/autoload/vimspector.vim b/autoload/vimspector.vim
index e2e3833..1094e68 100644
--- a/autoload/vimspector.vim
+++ b/autoload/vimspector.vim
@@ -320,28 +320,6 @@ function! vimspector#CompleteOutput( ArgLead, CmdLine, CursorPos ) abort
   return join( buffers, "\n" )
 endfunction

-py3 <<EOF
-def _vimspector_GetExprCompletions( ArgLead, prev_non_keyword_char ):
-  if not _vimspector_session:
-    return []
-
-  items = []
-  for candidate in _vimspector_session.GetCompletionsSync(
-    ArgLead,
-    prev_non_keyword_char ):
-
-    label = candidate.get( 'text', candidate[ 'label' ] )
-
-    start = prev_non_keyword_char - 1
-
-    if 'start' in candidate and 'length' in candidate:
-      start = candidate[ 'start' ]
-
-    items.append( ArgLead[ 0 : start ] + label )
-
-  return items
-EOF
-
 function! vimspector#CompleteExpr( ArgLead, CmdLine, CursorPos ) abort
   if !s:Enabled()
     return
```

then time it again:

```
time nvim -u support/minimal_vimrc +q
```

> Use the following Vimspector config file:

n/a

### Expected behaviour

> Provide A clear and concise description of what you expected to happen.

It shouldn't be slow.

### Actual behaviour

```
❯ time vim -u support/minimal_vimrc +q
nvim -p -u support/minimal_vimrc +q  0.12s user 0.05s system 91% cpu 0.184 total

~/github/vimspector (master)
❯ git stash pop && git diff
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   autoload/vimspector.vim

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (b2dd4b5e85f8398d152b7c6e7e957db6904d1dc3)
diff --git a/autoload/vimspector.vim b/autoload/vimspector.vim
index e2e3833..1094e68 100644
--- a/autoload/vimspector.vim
+++ b/autoload/vimspector.vim
@@ -320,28 +320,6 @@ function! vimspector#CompleteOutput( ArgLead, CmdLine, CursorPos ) abort
   return join( buffers, "\n" )
 endfunction

-py3 <<EOF
-def _vimspector_GetExprCompletions( ArgLead, prev_non_keyword_char ):
-  if not _vimspector_session:
-    return []
-
-  items = []
-  for candidate in _vimspector_session.GetCompletionsSync(
-    ArgLead,
-    prev_non_keyword_char ):
-
-    label = candidate.get( 'text', candidate[ 'label' ] )
-
-    start = prev_non_keyword_char - 1
-
-    if 'start' in candidate and 'length' in candidate:
-      start = candidate[ 'start' ]
-
-    items.append( ArgLead[ 0 : start ] + label )
-
-  return items
-EOF
-
 function! vimspector#CompleteExpr( ArgLead, CmdLine, CursorPos ) abort
   if !s:Enabled()
     return

~/github/vimspector (master)
❯ time vim -u support/minimal_vimrc +q
nvim -p -u support/minimal_vimrc +q  0.02s user 0.02s system 83% cpu 0.048 total
```

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

```
❯ git rev-parse HEAD
11edcddd9c6208d1290c1ff1fc1c598a3b963aca
```

* Output of `vim --version` or `nvim --version`

```
❯ ~/Desktop/nvim-osx64/bin/nvim --version
NVIM v0.5.0-dev+1112-ge55ded00c
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1614230343343.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

* Output of `which vim` or `which nvim`:

```
❯ which ~/Desktop/nvim-osx64/bin/nvim
/Users/jez/Desktop/nvim-osx64/bin/nvim
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
3.9.2 (default, Feb 19 2021, 17:09:53)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

* Output of `:py3 import vim`:

empty (is output expected?)

* Output of `:py3 import vimspector`:

empty (is output expected?)

* For neovim: output of `:checkhealth`

```

health#LanguageClient#check
========================================================================
  - OK: binary found: /Users/jez/.dotfiles/vim/bundle/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.158 
  - OK: Floating window is supported and will be used for hover

health#bettersml#check
========================================================================
## REPL
  - OK: REPL backend is available and valid: neovim
  - OK: SML/NJ is executable at 'sml'.
  - OK: rlwrap is available and will be used to launch REPLs

## Type information
  - OK: MLton is executable at 'mlton'.
  - OK: Support files are executable at '/Users/jez/.dotfiles/vim/bundle/vim-better-sml/bin/vbs-util'.

## General
  - OK: Asynchronous jobs are available.
  - WARNING: Running mlton in single-file mode.
    - ADVICE:
      - vim-better-sml usually looks for an MLB file to provide features
      - like type information and jump to definition. If your SML file is
      - actually part of a larger project, consider creating an MLB file.
      - See :help |vim-better-sml-mlbasis| for more information.
  - OK: Either ALE or Syntastic is installed.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 20ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.2 (outdated; from /usr/local/lib/python3.9/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.13.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

* Operating system: <linux or macOS> and version

macOS Catalina (10.15.7)
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes/No]

Yes

### PR DESCRIPTION
**Pull request by puremourning**
Fixes #361

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/362)

**Comment by puremourning** [comment]
@jez  does this fix it for you?

**Comment by jez** [comment]
> @jez does this fix it for you?

It's blazing fast now. Thanks!

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/362#-:-MUQFSuL-RiQr5RzxVfc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
