### PR TITLE
Check capabilities before sending instruction breakpoints

### PR DESCRIPTION
**Pull request by samisalreadytaken**
Servers can support disassembly without instruction breakpoints.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/855)

**Review by puremourning — COMMENTED** [review]
Thanks!

Do you have an example server that has this behaviour? Need to either write a test or see steps to reproduce and evidence that it fixes the issue.

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/855#-:-NxCD4HADSoPjTE0Y0-I:b2yjvag)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by samisalreadytaken** [comment]
It is the case in my currently unreleased server. It's caused by the lack of debugger interface on instruction execution while the instructions themselves and instruction pointers are accessible.

The simplest way to test locally would be to use a server that supports disassembly, and ignore/remove the `supportsInstructionBreakpoints` capability on `handle_initialize_response()` (and `OnEvent_capabilities()` if that server fires that event).

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks.

CI flake should be fixed.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/855#-:-NxCUgDQ2zPn3I6wR3sE:bsqr5ln)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @samisalreadytaken)

**Pull request merged**
