### PR TITLE
Add -t to docker exec to support colorful output

### PR DESCRIPTION
**Pull request by dcrblack**
Just adds a `-t` to the current `docker exec` command to support outputting colours in the output terminal when debugging code on a docker container

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/739)

**Comment by puremourning** [comment]
Cheers. Can you give an example where this is a problem? And can you evaluate what if any regression this might cause?

**Comment by dcrblack** [comment]
@puremourning Basically the terminal output does not get coloured when you debug some remote code via `docker exec`.

I have an example of this when I am debugging some Python tests that are ran in a docker container.

Before adding `-t`:

image

After adding `-t`:

image

I don't think the above changes will cause any regressions that I know of.

**Comment by puremourning** [comment]
I just have a vague memory that this came up or was discussed when the original PR added support for this docker exec. Then again I can't see why allocating a pty would be problematic..

**Review by puremourning — COMMENTED** [review]
I'll need to try this out at work where I use the docker executor frequently.

But I mean on the face of it, looks ok to me.

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/739#-:-NRUCY2g8FcwF0ydq1vG:bkhahac)* status: 0 of 1 files reviewed, all discussions resolved

**Review by puremourning — APPROVED** [review]
:lgtm:

THANKS!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/739#-:-NSM-glC1sF1pjWUfO7J:b-6c7s6x)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dcrblack)

**Review by puremourning — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dcrblack)

**Review by puremourning — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dcrblack)

**Comment by puremourning** [comment]
@MergifyIO retry

**Comment by puremourning** [comment]
@MergifyIO refresh

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/739#-:-NSMe-GyBVQIA6gYlwm2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dcrblack)

**Pull request merged**
