### PR TITLE
Add support for vim-repeat

### PR DESCRIPTION
**Pull request by JS-Zheng**
[vim-repeat](https://github.com/tpope/vim-repeat) is a popular Vim plugin that can use "`.`" to repeat `<Plug>`mappings or commands. I think this usage is very suitable for debuggers. 

This PR adds support for vim-repeat for stepping, breakpoint, frame and eval operations, which are usually used continuously during debugging.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/591)

**Review by puremourning — COMMENTED** [review]
Won’t this break everyone who _doesnt_ have the repeat plugin installed? 

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/591#-:-N20YWLk3-CyNoedNErT:bnl6vvn)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by JS-Zheng** [comment]
Yes, this change will not break users which doesn't install vim-repeat, and I have tested it pass. This's why I use `silent! ` command to call repeat#function, this is a common practice in plugins which use the `vim-repeat`.

**Comment by puremourning** [comment]
Looks like CI is failing. Did the tests pass for you

**Comment by JS-Zheng** [comment]
No, I didn't run CI test. I just triggered these  `<Plug>` mappings in the environment with `vim-repeat` and w/o `vim-repeat` respectively, then checked the behavior.
I think the failure of the CI may be due to **hidden** exceptions caused by `silent!`: `v:errmsg` is still set when `repeat#set()` function could not be found.
In spite of the behavior is correct,  I wrote a new version to catch these exceptions to try to pass CI test.

**Review by puremourning — CHANGES_REQUESTED** [review]
Thanks. few nits.

Can you also confirm how this was tested? Was every one of the repeats tested and confirmed working manually ?

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/591#-:-N2M57f415KmsRnKuHj1:b-6tm85t)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JS-Zheng and @puremourning)

___
*[`plugin/vimspector.vim` line 43 at r2](https://reviewable.io/reviews/puremourning/vimspector/591#-N2M4oRGDHU0TGSeOz6X:-N2M4oRGDHU0TGSeOz6Y:b86lfin) ([raw file](https://github.com/puremourning/vimspector/blob/64730435124f6bffee70e0cf28c00396b52845ce/plugin/vimspector.vim#L43)):*
> ```vim
> let s:mappings = get( g:, 'vimspector_enable_mappings', '' )
> 
> function! s:set_repeat( map )
> ```

please use existing style - `function! s:SetRepeat( map ) abort`
___
*[`plugin/vimspector.vim` line 46 at r2](https://reviewable.io/reviews/puremourning/vimspector/591#-N2M5-gP9KW1dKSCen21:-N2M5-gQA0t2XYfGRgaP:b-mlonna) ([raw file](https://github.com/puremourning/vimspector/blob/64730435124f6bffee70e0cf28c00396b52845ce/plugin/vimspector.vim#L46)):*
> ```vim
>   try
>     call repeat#set( a:map )
>   catch /^Vim\%((\a\+)\)\=:E117:/
> ```

please comment why this is necessary and what it does
___
*[`plugin/vimspector.vim` line 52 at r2](https://reviewable.io/reviews/puremourning/vimspector/591#-N2M4bTQ5d9GFjvvgDMf:-N2M4bTQ5d9GFjvvgDMg:birr0sg) ([raw file](https://github.com/puremourning/vimspector/blob/64730435124f6bffee70e0cf28c00396b52845ce/plugin/vimspector.vim#L52)):*
> ```vim
> nnoremap <silent> <Plug>VimspectorContinue
>       \ :<c-u>call vimspector#Continue()<CR>
>       \:<c-u>call <SID>set_repeat( "\<Plug>VimspectorContinue" )<CR>
> ```

please follow the existing indentation style (whitespace after backslash)

**Review by puremourning — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/591)* status: all files reviewed, 3 unresolved discussions (waiting on @JS-Zheng)

**Comment by JS-Zheng** [comment]
Hi @puremourning 
Thanks for your review, updates as below:
- [x] 1. update the function to the existing style
- [x] 2. add comments for the function
- [ ] 3. update mappings to the existing indentation style

The third point cannot be achieved, it should not add any whitespace after backslash for any mapping statement (except first one). Otherwise, users will trigger a `<Space>` and result in the cursor be moved one character right.
```
nnoremap <silent> <Plug>VimspectorContinue
      \ :<c-u>call vimspector#Continue()<CR>  <---- should add the leading space  to separate from `lhs` and `rhs`
      \:<c-u>call <SID>set_repeat( "\<Plug>VimspectorContinue" )<CR> <---- should **not** add the leading space
```

**Comment by JS-Zheng** [comment]
I test my changes by the following steps:

- Env w/ `repeat.vim` installed
  1. Trigger a repeatable mapping (e.g., `VimspectorToggleBreakpoint`)
  2. Check if the feature worked properly
  3. Repeat the mapping with the `.` command
  4. Check if the mapping was repeated and worked properly

- Env w/o `repeat.vim` installed
  1. Execute a repeatable native command (e.g., `dd`)
  2. Trigger a repeatable vimspector mapping (e.g., `VimspectorToggleBreakpoint`)
  3. Check if the feature worked properly
  4. Execute the `.` command
  5. Check if the `step 1` command was repeated rather than  the `stept 2` mapping

**Comment by JS-Zheng** [comment]
I ran the docker-container tests w/o my changes (clean vimspector clone), but still failed in some tests 🙁

Reproduction:
- clone vimspector
- `./tests/manual/run`
- `cd vimspector` (container shell)
- `./run_tests --install --basedir test-base-docker (container shell)`

container-tests-failed

**Comment by puremourning** [comment]
Great. Thanks for the detailed info. I'll take a look and probably merge tomorrow :)

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/591#-:-N4EM8xO34tajVilSIwN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JS-Zheng)

**Comment by puremourning** [comment]
Thanks!

**Pull request merged**
