### PR TITLE
Add a GetConfigurations function

### LINKED ISSUE #288: [Feature Request]: Function to get list of configuration names
**Describe the solution you'd like**
For example, a `vimspector#ListConfigurations()` function which would return a list of the launch configuration names

**Describe alternatives you've considered**
I could read the .vimspector.json file directly and parse, but figured a built-in function would be beneficial

**Additional context**
My goal would be to integrate with [telescope.vim](https://github.com/nvim-lua/telescope.nvim)

### PR DESCRIPTION
**Pull request by sharksforarms**
Fixes #288

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/289)

**Comment by sharksforarms** [comment]
Not 100% sure what's wrong with the MacOS build and if it's related to my changes

**Comment by puremourning** [comment]
> Not 100% sure what's wrong with the MacOS build and if it's related to my changes

May be a flake. I will re run it.

**Review by puremourning — CHANGES_REQUESTED** [review]
Wow. Thanks for sending a quality PR!

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/289#-:-MLPI6iiCQBBt4pXAJy-:b-lggo21)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @sharksforarms)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/289#-MLPGmHUEgMWHyYc1oRR:-MLPGmHVANNa-rX9y8O9:b-dgupzy) (no related file):*
Need to update README to document this api and maybe an example of how to use it (preferably with something like the built in matchfuzzy() function rather than some neovim only third party plugin). 

---
*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/289#-MLPGoWT9KFm71YxJsQE:-MLPGoWT9KFm71YxJsQF:b-hheqwp) (no related file):*
Needs tests. I won’t use this feature so it will be too easy for me to break it Without tests 

---
___
*[autoload/vimspector.vim, line 284 at r1](https://reviewable.io/reviews/puremourning/vimspector/289#-MLPHYzW4f9t3NlXWf1Z:-MLPHYzW4f9t3NlXWf1_:b-q51utu) ([raw file](https://github.com/puremourning/vimspector/blob/719e974bb34a51583833555d8a2fcd299f4056cc/autoload/vimspector.vim#L284)):*
> ```vim
>     return
>   endif
>   let configurations = py3eval( 'list(_vimspector_session.ListConfigurations()[1].keys())'
> ```

Spaces inside parentheses, braces and brackets. 
___
*[autoload/vimspector.vim, line 286 at r1](https://reviewable.io/reviews/puremourning/vimspector/289#-MLPGw4i4pwrJi2NuQjG:-MLPGw4i4pwrJi2NuQjH:b-4xho5l) ([raw file](https://github.com/puremourning/vimspector/blob/719e974bb34a51583833555d8a2fcd299f4056cc/autoload/vimspector.vim#L286)):*
> ```vim
>   let configurations = py3eval( 'list(_vimspector_session.ListConfigurations()[1].keys())'
>                               \ . ' if _vimspector_session else []' )
>   return join( configurations, "\n" )
> ```

I think we should return the list as a list, why are we returning a new line separated string ?
___
*[python3/vimspector/debug_session.py, line 83 at r1](https://reviewable.io/reviews/puremourning/vimspector/289#-MLPHChN9NxndsErvcNC:-MLPHChN9NxndsErvcND:b-1wt86g) ([raw file](https://github.com/puremourning/vimspector/blob/719e974bb34a51583833555d8a2fcd299f4056cc/python3/vimspector/debug_session.py#L83)):*
> ```Python
> 
>   def ListConfigurations( self ):
>     current_file = utils.GetBufferFilepath( vim.current.buffer )
> ```

This is really GetConfigurations rather than List them. 
___
*[python3/vimspector/debug_session.py, line 102 at r1](https://reviewable.io/reviews/puremourning/vimspector/289#-MLPGcch1NKJXL2DY8X8:-MLPGcch1NKJXL2DY8X9:bh5jn8n) ([raw file](https://github.com/puremourning/vimspector/blob/719e974bb34a51583833555d8a2fcd299f4056cc/python3/vimspector/debug_session.py#L102)):*
> ```Python
>                          'You need to tell vimspector how to launch your '
>                          'application.' )
>       return
> ```

Needs to return a 2-tuple and calling code needs to abort. Or maybe move this block out of this function.

**Review by puremourning — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/289)* status: all files reviewed, 6 unresolved discussions (waiting on @sharksforarms)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/289)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @puremourning and @sharksforarms)

___
*[README.md, line 681 at r2](https://reviewable.io/reviews/puremourning/vimspector/289#-MLTK-W7-D7iAWHlywai:-MLTK-W7-D7iAWHlywaj:bv4b5gk) ([raw file](https://github.com/puremourning/vimspector/blob/23a3d81403d2dd02d2b859db97d6c8b55363e0d3/README.md#L681)):*
> ```Markdown
> Here's an example fuzzy matcher prompt to select a launch configuration
> ```viml
> :call vimspector#LaunchWithSettings(matchfuzzy(vimspector#GetConfigurations(), input("Fuzzy Launch: ")))
> ```

did you test this works ?

I don't think it does because `LaunchWithSettings` takes a dict, needs to be `{ 'configuration': match.... }`
___
*[autoload/vimspector.vim, line 284 at r1](https://reviewable.io/reviews/puremourning/vimspector/289#-MLPHYzW4f9t3NlXWf1Z:-MLTJk-c37nS6wECm_0X:b9opc4c) ([raw file](https://github.com/puremourning/vimspector/blob/719e974bb34a51583833555d8a2fcd299f4056cc/autoload/vimspector.vim#L284)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Spaces inside parentheses, braces and brackets. 
</blockquote></details>

this looks suspiciously like it's longer than 80 characters ? is it ?

**Comment by sharksforarms** [comment]
> > Here's an example fuzzy matcher prompt to select a launch configuration
> > ```viml
> > :call vimspector#LaunchWithSettings(matchfuzzy(vimspector#GetConfigurations(), input("Fuzzy Launch: ")))
> > ```
> 
> did you test this works ?
> 

Quick to review! I was trying to test using the latest vim/plugged from my fork, but I can't get it to work w/ python and latest vim... could you help me with a vim example? I'm using neovim.

I still need to add tests.

**Comment by sharksforarms** [comment]
I may need help with the tests, my viml knowledge is minimal. Looking into this now.

**Comment by sharksforarms** [comment]
@puremourning Ready for another look

**Review by puremourning — APPROVED** [review]
NICE.

:lgtm: 

I'm re-running the tests. Ugh. Flakes.

> Reviewed 1 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/289#-:-MLT_HxRC0q6dlIjmr8m:b-go8x6e)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
