### PR TITLE
Fix shutdown sequence for channel-based servers

### LINKED ISSUE #55: Vimspector is not properly shutting down when Reset is called
**Describe the bug**

After calling `vimspector#Reset()` while debugging a java application using the eclipse.jdt.ls via YouCompleteMe, vimspector never resets. The vim tab remains open and the final messages logged by vimspector indicate the events that fire on exit are never called.

**To Reproduce**
List of steps to reproduce

1. Create an example java project using maven. Configure YouCompleteMe to use the eclipse.jdt.ls to perform completion (and to enable debugging)
1. Download the vscode java debugger extension, place it in your home directory
1. Set the following in your .vimrc: `let g:ycm_java_jdtls_extension_path = [ '<your home dir>/<your vscode extensions directory>/' ]`
1. Drop a breakpoint in a file in the project you desire to debug
1. Call `YcmCompleter ExecuteCommand vscode.java.startDebugSession`
1. Call `vimspector#Launch()`
1. Enter the port provided by YouCompleteMe to start vimspector
1. Once the debugger has attached, call `vimspector#Reset()`

Vimspector config file:

```
{
    "adapters": {
        "java-debug-server": {
            "name": "vscode-java",
            "port": "ask"
        }
    },
    "configurations": {
        "Java Launch": {
            "adapter": "java-debug-server",
            "configuration": {
                "request": "attach",
                "hostName": "localhost",
                "port": "5005",
                "sourcePaths": [ "${workspaceRoot}/**" ],
                "classPaths": [ "${workspaceRoot}/**/target/classes" ],
                "args": "",
                "stopOnEntry": true,
                "console": "integratedTerminal"
            }
        }
    }
}
```

**Expected behavior**

I'd expect vimspector to close the tab that was opened when vimspector was launched and for vimspector to be ready to be used again (i.e., calling `vimspector#Launch()` again)

**Actual behaviour**
What actually happened, including output, log files etc.

Please include:
* Vimspector log (~/.vimspector.log)
* Output from any or all UI diagnostic tabs (Server, etc.)

The tab never closes; it remains open and vimspector is never put into a clean slate. If `vimspector#Launch()` is called again, vimspector dumps a bunch of erroneous output. 

I can't dump the entire .vimspector.log here since it contains some work-related information. Here is the relevant information at the end of the file though:

* Note that the contents below do contain all of the output at the end of the log; there is no other output below this

```
2019-10-01 14:52:57,903 - DEBUG - Message received: {'event': 'thread', 'body': {'reason': 'exited', 'threadId': 76, 'type': 'thread'}, 'seq': 395, 'type': 'event'}
2019-10-01 14:52:57,903 - DEBUG - Message received: {'event': 'exited', 'body': {'exitCode': 0, 'type': 'exited'}, 'seq': 396, 'type': 'event'}
2019-10-01 14:52:57,903 - INFO - User Msg: The debugee exited with status code: 0
2019-10-01 14:52:57,903 - DEBUG - Message received: {'event': 'exited', 'body': {'exitCode': 0, 'type': 'exited'}, 'seq': 397, 'type': 'event'}
2019-10-01 14:52:57,904 - INFO - User Msg: The debugee exited with status code: 0
2019-10-01 14:53:01,463 - DEBUG - Stop debug adapter with callback : self._Reset()
2019-10-01 14:53:01,464 - DEBUG - Sending Message: {"command": "disconnect", "arguments": {"terminateDebuggee": true}, "seq": 25, "type": "request"}
2019-10-01 14:53:01,465 - DEBUG - Message received: {'success': True, 'request_seq': 25, 'command': 'disconnect', 'seq': 398, 'type': 'response'}
2019-10-01 14:53:01,465 - DEBUG - Setting server exit handler before disconnect
```

If I call `vimspector#Launch()` again after calling `vimspector#Reset()`, the following output is returned:

```
Error detected while processing function vimspector#Launch:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_session.py", line 165, in Start
    self._StartWithConfiguration( configuration, adapter )
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_session.py", line 213, in _StartWithConfiguration
    start()
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_session.py", line 181, in start
    self._SetUpUI()
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_session.py", line 363, in _SetUpUI
    vim.current.buffer )
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/stack_trace.py", line 33, in __init__
    utils.SetUpScratchBuffer( self._buf, 'vimspector.StackTrace' )
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/utils.py", line 88, in SetUpScratchBuffer
    buf.name = name
vim.error: Vim:E95: Buffer with this name already exists
Press ENTER or type command to continue
```
Of course this is due to the buffers never actually being closed when reset is called.

**Environemnt**

NOTE: NeoVim is not supported.
NOTE: Windows is not supported.

* Output of `vim --version`

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 03 2019 13:04:21)
Included patches: 1-1967
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        +mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-I6gBP8/vim-8.1.1967=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm
```

* Output of `which vim`:

```
/usr/bin/vim
```

* Output of `:py3 pass`:

This isn't printing anything in my Vim version for whatever reason.

* Operating system: <linux or macOS> and version

Ubuntu 16.04 

**Additional context**

### PR DESCRIPTION
**Pull request by puremourning**
Fixes #55 

The `channel` based servers were broken in the refactor of the closedown sequence. 

We now call `OnServerExit` from the channel close callback, and also call that manually from the `StopDebugSession` method. Note: `close_cb` is _not_ called when closing a channel using `ch_close` hence we have to call it manually in that case.

@peanutbutterspice

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/57)

**Comment by peanutbutterspice** [comment]
Can confirm that last scenario you mentioned will happen:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_session.py", line 227, in OnChannelData
    self._connection.OnData( data )
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_adapter_connection.py", line 131, in OnData
    self._ReadBody()
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_adapter_connection.py", line 205, in _ReadBody
    self._OnMessageReceived( message )
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_adapter_connection.py", line 228, in _OnMessageReceived
    request.handler( message )
  File "/home/devynmapes/.vim/pack/my-plugins/start/vimspector/python3/vimspector/debug_session.py", line 464, in handler
    self._connection_type ) )
vim.error: Vim(unlet):E108: No such variable: "s:ch"
```

Aside from that I can confirm that this does fix the issue.

**Comment by puremourning** [comment]
> Can confirm that last scenario you mentioned will happen:

Did you repro that with the latest version of the PR ? If so, could you let me know how ? I thought it was fixed...

**Comment by peanutbutterspice** [comment]
No; vimspector does properly reset as far as I can tell. The error I posted above does get dumped to the messages though. Did a quick check and it is definitely from `unlet s:ch` on line 36

**Comment by puremourning** [comment]
> The error I posted above does get dumped to the messages though.

Even after I removed the `unlet` from `StopDebugSession` ? I can't see how that's possible unless we're getting the callback twice :(

Doens't repro for me ...

**Comment by peanutbutterspice** [comment]
Ah, figured out the issue. It was on my end; you can disregard my above comment. Sorry about that!

**Comment by puremourning** [comment]
Wonderful! Let's ship it then!

**Pull request merged**
