### PR TITLE
nodejs is required for php debugging for vscode-php-debug

### PR DESCRIPTION
**Pull request by dni**
it took me literally 1 day to figure this out why it was not working on 1 of my server :D no errors what so ever just a silent fail, you need to have ```node``` command wokring.

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/516)

**Review by puremourning — CHANGES_REQUESTED** [review]
Thanks for the PR!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/516#-:-MtSne335wUbPyAkujJi:b-ek0rh5)* status: all files reviewed, 2 unresolved discussions (waiting on @dni)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/puremourning/vimspector/516#-MtSnGkB6CVhciDwRTcA):*
I do t think we need this comment in the comment message. 
___
*[README.md, line 168 at r1](https://reviewable.io/reviews/puremourning/vimspector/516#-MtSnX8e3djtaOfTGVrk:-MtSnX8h9zzPazdZH_32:be4oanr) ([raw file](https://github.com/puremourning/vimspector/blob/2e143de3621ac332de274dabba86aabb75da5234/README.md#L168)):*
> ```Markdown
> | Go (legacy)          | Legacy      | `--enable-go`                      | vscode-go                            | Node, Go, [Delve][]                          |
> | C# (mono)            | _Retired_   | N/A                                | N/A                                  | N/A                                          |
> | Python.legacy        | _Retired_   | N/A                                | N/A                                  | N/A                                          |
> ```

It seeems php is masing from this table. We should probably add it here too.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/516)* status: all files reviewed, 3 unresolved discussions (waiting on @dni)

___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/puremourning/vimspector/516#-MtbhQra13Z3F6wKH-v_):*
use `--help` ?
___
*[README.md, line 164 at r2](https://reviewable.io/reviews/puremourning/vimspector/516#-Mtbh8jr8z0sYhnMlI4e:-Mtbh8jr8z0sYhnMlI4f:b-9g2mpj) ([raw file](https://github.com/puremourning/vimspector/blob/041f7f976fa51e22ad6e468fa03aa7aee52dd6ac/README.md#L164)):*
> ```Markdown
> | Javascript           | Supported   | `--force-enable-firefox`           | vscode-firefox-debug                 | Firefox                                      |
> | Java                 | Supported   | `--force-enable-java  `            | vscode-java-debug                    | Compatible LSP plugin (see [later](#java))   |
> | PHP                  | Supported   | `--force-enable-php`               | vscode-php-debug                     | 6 < Node < 12, Npm, PHP, XDEBUG              |
> ```

Supported -> Experimental

I don't use or test this often, so I can't claim to be able to support it.

Also are we sure that node < 12 is required ? I'd rather just put that node is required. Is npm really required?

**Review by dni — COMMENTED** [review]
added experimental, removed npm and node version number

**Review by puremourning — APPROVED** [review]
:lgtm:

thanks.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/516#-:-MtbiXxm2S2uSNr372Qn:b-i7on70)* status: all files reviewed, 2 unresolved discussions (waiting on @dni)

**Review by dni — COMMENTED** [review]
fine for me :)

**Review by puremourning — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/516#-:-MtbqUP_0uwZdzTqR2j5:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dni)

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dni)

**Pull request merged**
