### PR TITLE
Bump vscode-lldb to 1.9.0

### PR DESCRIPTION
**Pull request by mark2185**

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/728)

**Comment by mark2185** [comment]
Could the C# tests really be failing due to `CodeLLDB` update?

I don't have a mac I could debug this on.

**Comment by puremourning** [comment]
Sigh I will try and take a look

**Comment by puremourning** [comment]
Thanks for the PR

**Comment by mark2185** [comment]
No problem! 

Also sorry for the hassle.

**Comment by puremourning** [comment]
not your fault. I mean for some reason, the tests just stop working. Like they are sentient or something.

**Comment by puremourning** [comment]
tests pass on my laptop (arm64) and my iMac (x64) so as usual the issue is likely just GHA Macs being excruciatingly slow (best guess).

**Pull request merged**
