### PR TITLE
avoid unnecessary string concat

### PR DESCRIPTION
**Pull request by timsu92**
## About this PR
- I've searched for `vimspector#CompleteOutput` and didn't find other references.
- As [this line](https://github.com/puremourning/vimspector/blob/3378018bc1cdd1d9b70734c3e970bc52fd983415/python3/vimspector/output.py#L60) indicates, `vimspector#CompleteOutput` won't return a list with items not an instance of string; hence nothing will be ignored by `customlist`
- I've tested this by command `:VimspectorShowOutput` **_on Vim 8.2 only, and I don't use neovim_**

## About RFC
I'm thinking of another feature which will be based on this PR, but not related to the title. So I'm concealing below.
<details>

I would like to add a command `VimspectorShowBuffer` which allows one to faster switch faster among all the buffers.
In order to do this, I'm considering making use of `vimspector#CompleteOutput()` and `g:vimspector_session_windows` to be the completion of the new command.
</details>

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/669)

**Comment by timsu92** [comment]
It's been so long since I last heard form you!
I apologize if I should complete the code about RFC as well instead of waiting for this to be approved and then do that.
If I'm missing anything, please let me know!

**Comment by puremourning** [comment]
I’m on vacation. Back next week.

**Comment by timsu92** [comment]
Sure! Take your time!

**Comment by puremourning** [comment]
Thanks, this is fine.

>  I'm considering making use of vimspector#CompleteOutput() and g:vimspector_session_windows to be the completion of the new command.

I'm not sure exactly what this other feature is, or how this relates, but we can discuss that separately.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/669#-:-NCeAg4h-zucAvWPGBmG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @timsu92)

**Pull request merged**
