### PR TITLE
multiple languages per adapter

### LINKED ISSUE #274: [Feature Request]: Support F#
That should not be too hard, because F# runs on .NET core and mono, so the actual debuggers should work out of the box.

### PR DESCRIPTION
**Pull request by yatli**
closes #274

### CODE REVIEW

**Comment by puremourning** [comment]
This change is [Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317)

**Review by puremourning — CHANGES_REQUESTED** [review]
Thanks for this! I was actually recently mulling a similar change, though I backed out of it because it means that we end up installing maybe more stuff than people _need_. That said, if people are using `:VimspectorInstall` and the auto-install stuff, it's less of a problem I think.

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317#-:-MOXeoay0Ot1soE03K0S:b-jn9j29)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @yatli)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/317#-MOXepnQCMAKedo2d_x2:-MOXepnQCMAKedo2d_x3:b-uh2g8c) (no related file):*
Need to update the documentation

---
*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/317#-MOXerL0EGvwPv3xZLLN:-MOXerL0EGvwPv3xZLLO:b667ju5) (no related file):*
Please can you describe how you tested this such taht I could repeat your tests for a future change. Ideally we should add regression tests for this, though maybe the existing install/update tests cover that.

---
___
*[install_gadget.py, line 118 at r1](https://reviewable.io/reviews/puremourning/vimspector/317#-MOXeDuu47y4bhW3hUJz:-MOXeDuu47y4bhW3hUK-:bnj93rm) ([raw file](https://github.com/puremourning/vimspector/blob/28c5534704ea4b8ec9207220d0bb6b3932581824/install_gadget.py#L118)):*
> ```Python
> for name, gadget in gadgets.GADGETS.items():
>   langs = gadget[ 'language' ]
>   if not isinstance(langs, list): langs = [langs]
> ```

newline + indent
___
*[install_gadget.py, line 188 at r1](https://reviewable.io/reviews/puremourning/vimspector/317#-MOXeKJ448RqZVQmZw-v:-MOXeKJ448RqZVQmZw-w:bnj93rm) ([raw file](https://github.com/puremourning/vimspector/blob/28c5534704ea4b8ec9207220d0bb6b3932581824/install_gadget.py#L188)):*
> ```Python
> for name, gadget in gadgets.GADGETS.items():
>   langs = gadget[ 'language' ]
>   if not isinstance(langs, list): langs = [langs]
> ```

newline + indent
___
*[install_gadget.py, line 203 at r1](https://reviewable.io/reviews/puremourning/vimspector/317#-MOXeMnk3yS_eJjPahZY:-MOXeMnk3yS_eJjPahZZ:b-5xozqw) ([raw file](https://github.com/puremourning/vimspector/blob/28c5534704ea4b8ec9207220d0bb6b3932581824/install_gadget.py#L203)):*
> ```Python
>         skip = skip + 1
>         continue
>   if skip == len(langs): continue
> ```

new line + indent
___
*[python3/vimspector/gadgets.py, line 24 at r1](https://reviewable.io/reviews/puremourning/vimspector/317#-MOXePnD-MAFDf8H-4cC:-MOXePnD-MAFDf8H-4cD:b-t6ffl7) ([raw file](https://github.com/puremourning/vimspector/blob/28c5534704ea4b8ec9207220d0bb6b3932581824/python3/vimspector/gadgets.py#L24)):*
> ```Python
> GADGETS = {
>   'vscode-cpptools': {
>     'language': ['c','cpp'],
> ```

`, 'rust'`
___
*[python3/vimspector/installer.py, line 233 at r1](https://reviewable.io/reviews/puremourning/vimspector/317#-MOXeXvLBXxuaZJqeKVi:-MOXeXvLBXxuaZJqeKVj:b-5xozqw) ([raw file](https://github.com/puremourning/vimspector/blob/28c5534704ea4b8ec9207220d0bb6b3932581824/python3/vimspector/installer.py#L233)):*
> ```Python
> 
>     lang = gadget[ "language" ]
>     if isinstance(lang, list): lang = lang[0]
> ```

new line + indent

**Comment by yatli** [comment]
thanks for the feedback, I've updated things a bit.

**Comment by puremourning** [comment]
Thanks. Still some lint error and need to rebase. 

Sorry for the delay looking at this, I have a ton on at the moment.

**Comment by yatli** [comment]
me python noob :D

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317)* status: all files reviewed, 5 unresolved discussions (waiting on @yatli)

___
*[install_gadget.py, line 129 at r4](https://reviewable.io/reviews/puremourning/vimspector/317#-MPA9QXz9cqGIykgj2OF:-MPA9QXz9cqGIykgj2OG:b-s4l43y) ([raw file](https://github.com/puremourning/vimspector/blob/f59ba048cbdcaf04feee370b3651b2342cedfcb6/install_gadget.py#L129)):*
> ```Python
>         '--force-enable-' + lang,
>         action = 'store_true',
>         help = 'Install the unsupported {} debug adapter for {} support'.format(
> ```

this message (and the other help messages) are now a bit wrong it only mentioned the _first_ adapter.

I think perhaps this should actually include all of them? or maybe none of them... ? wdyt ?
___
*[install_gadget.py, line 197 at r4](https://reviewable.io/reviews/puremourning/vimspector/317#-MPAA37m9kwmhpjb9WzL:-MPAA37m9kwmhpjb9WzM:b7fscf6) ([raw file](https://github.com/puremourning/vimspector/blob/f59ba048cbdcaf04feee370b3651b2342cedfcb6/install_gadget.py#L197)):*
> ```Python
>            and not getattr( args, 'force_enable_' +  lang ) ):
>         skip = skip + 1
>         continue
> ```

we can remove these `continue` statements; they are just confusing now (it's continuing the inner loop, but there are no more statements outside of this if/else.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317)* status: all files reviewed, 5 unresolved discussions (waiting on @yatli)

___
*[install_gadget.py, line 197 at r4](https://reviewable.io/reviews/puremourning/vimspector/317#-MPAA37m9kwmhpjb9WzL:-MPAABPG8LF4jPjOZyXT:bf4i12t) ([raw file](https://github.com/puremourning/vimspector/blob/f59ba048cbdcaf04feee370b3651b2342cedfcb6/install_gadget.py#L197)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

we can remove these `continue` statements; they are just confusing now (it's continuing the inner loop, but there are no more statements outside of this if/else.
</blockquote></details>

TBH this might be better written something like

```python
def CheckGadgetIncluded( lang ):
  # this block of code

if not any( CheckGadgetIncluded( lang ) for lang in langs ):
  continue
```

I prefer that because the `skip` variable feels a little tacky

**Comment by puremourning** [comment]
Hmmm. I tested this by doing something like:

* set vscode-cpptools languages to `[ 'c', 'cpp', 'rust' ]`
* set CodeLDB languages to `[ 'c', 'cpp', 'rust' ]`
* `./install_gadget.py --all --disable-rust`

This does not prevent either vscode-cpptools or CodeLLDB being installed. I'm not sure if that's good or bad.

**Comment by puremourning** [comment]
Also, if I clear out my gadgets directory, then open a c++ file and do F5, I get offered to install `CodeLLDB`, but it actually installs _both_ `CodeLLDB` and `vscode-cpptools`.

So I think that we have a little problem where we're mapping those concepts. Maybe the solution to that is for the script to accept `--enable-gadget-<name>` instead of having the python code try and guess the right arguments. that's getting a little complex though :/

**Comment by yatli** [comment]
Thanks for testing out!
I've been having a lot of fun with vimspector+gdb for debugging an ancient copy of gcc 1.37, and also had success with F# debugging with this patch.

> So I think that we have a little problem where we're mapping those concepts. Maybe the solution to that is for the script to accept --enable-gadget-<name> instead of having the python code try and guess the right arguments. that's getting a little complex though :/

I think this is reasonable. An analogy from `coc.nvim` is that it has `coc-python`, `coc-pyright` and `coc-jedi` and you cannot simply ask it to install the best option for the python language.

The situation is similar for VSCode -- it will recommend you to install the MS C++ extension but if that doesn't work out, you can alternatively choose to install, for example, a clang-based language server extension.

**Comment by puremourning** [comment]
The reason that the installer initially was filetype based is that it's a simpler message for most users. "I just want it to work with <language>". Too many choices means that people don't know what to choose and have no experience on which to base that choice. It's a tricky problem. In the case of the "automatic" installation of the gadget, the user _already_ chose (by putting `"adapter": "vscode-cpptools"` or something in their `.vimspector.json` and chosing that debug config) so it's ok to be explicit about the gadget being installed.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @puremourning and @yatli)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/317#-MQagZPV1x7jkQzy8sS0:-MQagZPW6W9M6Ni1cjWN:bbwg6e5) (no related file):*
Per this comment: https://github.com/puremourning/vimspector/pull/317#issuecomment-752476139

We need to avoid it redundantly installing gadgets when auto installation runs.

---

**Review by puremourning — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/317#-MQagZPV1x7jkQzy8sS0:-MQagyn03TE9-wwxa13v:bj4m4rz) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Per this comment: https://github.com/puremourning/vimspector/pull/317#issuecomment-752476139

We need to avoid it redundantly installing gadgets when auto installation runs.
</blockquote></details>

On reflection, this probably isn't a new issue. So can ignore this.

---
___
*[python3/vimspector/installer.py, line 234 at r5](https://reviewable.io/reviews/puremourning/vimspector/317#-MQagnQ0DgS7HF5ZkTh_:-MQagnQ0DgS7HF5ZkTha:b-mvk3q2) ([raw file](https://github.com/puremourning/vimspector/blob/38ed75dda7577f6d2ac96f17518cfc23f127a344/python3/vimspector/installer.py#L234)):*
> ```Python
>     lang = gadget[ "language" ]
>     if isinstance( lang, list ):
>       lang = lang[ 0 ]
> ```

I think this doesn't work exactly when you have 2 gadgets for the same language.

But come to think of it, that was always true, so I think it's fine.

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317#-:-MQahOfQ37hF1Zjh5Etx:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @puremourning)

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/317#-:-MQayi3REj88iD2X9hA-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
